const test=require('node:test'),assert=require('node:assert/strict'),{loader}=require('./tenh-seven/harness.cjs');
function setup({fail=false,hidden=['private']}={}){
 const calls=[],rpc=[];const now=Date.now();
 const members=[{id:'m',business_id:'a',is_active:true,full_name:'Fixture Member'}];
 const conversations=Array.from({length:1001},(_,i)=>({id:'c'+i,business_id:'a',social_account_id:'shared',assigned_to:'m',status:'open',unread_count:i===0?5:0}));
 conversations.push({id:'hidden',business_id:'a',social_account_id:'private',assigned_to:'m',status:'open',unread_count:99},{id:'foreign',business_id:'b',social_account_id:'shared',assigned_to:'m',status:'open',unread_count:99});
 const reminders=[{id:'r1',business_id:'a',assigned_to:'m',status:'open',remind_at:new Date(now-1000).toISOString(),conversation:{business_id:'a',social_account_id:'shared'}},{id:'r2',business_id:'a',assigned_to:'m',status:'open',remind_at:new Date(now-1000).toISOString(),conversation:{business_id:'a',social_account_id:'private'}},{id:'r3',business_id:'a',assigned_to:'m',status:'open',remind_at:new Date(now-1000).toISOString(),conversation:{business_id:'b',social_account_id:'shared'}}];
 class Query{constructor(table){this.table=table;this.filters=[]}select(s){this.selectText=s;return this}eq(k,v){this.filters.push([k,'eq',v]);return this}in(k,v){this.filters.push([k,'in',v]);return this}filter(k,op,v){this.filters.push([k,op,v]);return this}order(){return this}range(a,b){return this.read(a,b)}then(resolve,reject){return this.read().then(resolve,reject)}async read(a=0,b=Infinity){calls.push({table:this.table,filters:this.filters,select:this.selectText,range:[a,b]});if(fail&&this.table==='conversation_reminders')return{data:null,error:{message:'Synthetic read failure'}};const rows=({team_members:members,conversations,conversation_reminders:reminders})[this.table];return{data:rows.filter(row=>this.filters.every(([k,op,v])=>{const x=k.split('.').reduce((o,p)=>o?.[p],row);return op==='eq'?x===v:op==='in'?v.includes(x):!v.includes(x)})).slice(a,b+1),error:null};}}
 const load=loader({'@/lib/auth/get-current-member':{getCurrentMember:async()=>({success:true,user:{id:'u'},member:{id:'m',business_id:'a',role:'owner'}})},'@/lib/telegram-personal/visibility':{hiddenPersonalAccountIds:async()=>hidden,hiddenAccountInList:ids=>ids.length?'('+ids.join(',')+')':null},'@/lib/supabase/admin':{supabaseAdmin:{from:t=>new Query(t),rpc:async(name)=>{rpc.push(name);return{data:null,error:{message:'Missing proposal'}}}}}});
 return{calls,rpc,get:async(query='')=>{const r=await load('app/api/team/workload/route.ts').GET({nextUrl:new URL('https://fixture.invalid?'+query)});return{status:r.status,body:await r.json()};}};
}
test('workload pages past 1000 rows, labels unread unit accurately, filters joined reminders before counting',async()=>{
 const f=setup(),r=await f.get('includeLive=1');assert.equal(r.status,200);assert.equal(r.body.members[0].activeCount,1001);assert.equal(r.body.members[0].unreadCount,5);assert.equal(r.body.members[0].overdueReminders,1);assert.equal(r.body.live,null);assert.equal(f.rpc.length,0);
 assert.deepEqual(f.calls.filter(c=>c.table==='conversations').map(c=>c.range),[[0,999],[1000,1999]]);assert.match(f.calls.find(c=>c.table==='conversation_reminders').select,/conversations!inner/);
});
test('workspace mismatch stops workload reads and failed reminder page never publishes zero',async()=>{const f=setup();assert.equal((await f.get('businessId=b')).status,409);assert.equal(f.calls.length,0);const failed=await setup({fail:true}).get();assert.equal(failed.status,500);assert.equal(failed.body.members,undefined);});
test('existing unrestricted live workload absence is displayed unavailable rather as zero',async()=>{const f=setup({hidden:[]}),r=await f.get('includeLive=1');assert.equal(r.status,200);assert.equal(r.body.live,null);assert.match(r.body.liveError,/unavailable/);assert.deepEqual(f.rpc,['get_tenh_live_workload']);});
