const test=require('node:test'),assert=require('node:assert/strict');
const {loader}=require('./tenh-seven/harness.cjs');
const api=loader({})('lib/bot/draft-rules.ts');
const ctx={businessId:'b1',channelId:'p1',now:'2026-10-01T12:30:00Z',staff:[{id:'m1',load:0},{id:'m2',load:0}]};
const rule=(kind='keyword_faq',extra={})=>({id:'r1',kind,businessId:'b1',channelId:'p1',name:'Fixture',mode:'draft',priority:50,cooldownMinutes:60,keywords:['price'],template:'Tenant configured reply',awayTemplate:'Tenant away',timezone:'UTC',hours:[{day:4,start:540,end:1020}],memberIds:[],assignOnIncoming:false,alertMinutes:15,menu:[],...extra});
const event=(extra={})=>({id:'e1',conversationId:'c1',recipientId:'u1',at:'2026-10-01T12:00:00Z',kind:'customer',text:'price',...extra});
const plan=(rules,events=[event()])=>api.previewDraftRules(rules,events,ctx);
test('draft plan has no live execution and templates remain tenant configured',()=>{const p=plan([rule()]);assert.equal(p.dryRun,true);assert.equal(p.executionAvailable,false);assert.equal(p.actions[0].text,'Tenant configured reply');});
test('foreign business/channel and enabled modes are rejected',()=>{for(const x of [{businessId:'foreign'},{channelId:'foreign'},{mode:'enabled'}])assert.throws(()=>plan([rule('keyword_faq',x)]));});
test('bounded inputs reject too many rules/events, invalid timezone and empty FAQ',()=>{assert.throws(()=>plan(Array.from({length:21},(_,i)=>rule('keyword_faq',{id:String(i)}))));assert.throws(()=>plan([rule()],Array.from({length:101},()=>event())));assert.throws(()=>plan([rule('keyword_faq',{timezone:'bad'})]));assert.throws(()=>plan([rule('keyword_faq',{keywords:[]})]));});
test('higher priority wins; equal priorities use stable ID precedence without mutating inputs',()=>{const rows=[rule('keyword_faq',{id:'z',priority:10,template:'low'}),rule('keyword_faq',{id:'a',priority:90,template:'high'})];assert.equal(plan(rows).actions[0].text,'high');assert.equal(rows[0].id,'z');});
test('duplicate and out-of-order events yield one reply and recipient cooldown spans conversations',()=>{const p=plan([rule()],[event({id:'e2',conversationId:'c2',at:'2026-10-01T12:01:00Z'}),event(),event()]);assert.equal(p.actions.filter(a=>a.kind==='reply').length,1);});
test('bot events and future events never trigger draft actions; expired direct window refuses replies',()=>{assert.equal(plan([rule()],[event({kind:'bot'}),event({id:'later',at:'2026-10-02T00:00:00Z'})]).actions.length,0);assert.equal(plan([rule()],[event({at:'2026-09-30T12:00:00Z'})]).actions.length,0);});
test('welcome only first contact during hours, away outside hours',()=>{const r=rule('welcome_away');assert.equal(plan([r],[event({firstContact:true})]).actions[0].text,r.template);assert.equal(plan([r],[event({firstContact:false})]).actions.length,0);assert.equal(plan([r],[event({at:'2026-10-01T08:00:00Z'})]).actions[0].text,r.awayTemplate);});
test('business hours honor overnight rollover, timezone and DST-local minutes',()=>{const r=rule('welcome_away',{hours:[{day:3,start:1320,end:120}]});assert.equal(api.withinDraftHours(r,'2026-10-01T01:00:00Z'),true);assert.equal(api.withinDraftHours(r,'2026-10-01T03:00:00Z'),false);const ny=rule('welcome_away',{timezone:'America/New_York',hours:[{day:0,start:60,end:120}]});assert.equal(api.withinDraftHours(ny,'2026-11-01T05:30:00Z'),true);assert.equal(api.withinDraftHours(ny,'2026-11-01T06:30:00Z'),true);});
test('human takeover preempts FAQ and assigns only existing selected staff once',()=>{const p=plan([rule(),rule('human_takeover',{id:'handoff',keywords:['price'],memberIds:['m1'],assignOnIncoming:true})],[event(),event({id:'e2'})]);assert.equal(p.actions.filter(a=>a.kind==='reply').length,0);assert.equal(p.actions.filter(a=>a.kind==='assign').length,1);assert.equal(p.actions.find(a=>a.kind==='assign').memberId,'m1');assert.throws(()=>plan([rule('human_takeover',{memberIds:['foreign']})]));});
test('existing sample assignment is never overwritten',()=>{const p=api.previewDraftRules([rule('human_takeover',{memberIds:['m1'],assignOnIncoming:true})],[event()],{...ctx,assignments:[{conversationId:'c1',memberId:'m2'}]});assert.equal(p.actions.filter(a=>a.kind==='assign').length,0);});
test('staff reply cancels unanswered alert and holds replies until explicit resume',()=>{const p=plan([rule(),rule('unanswered_alert',{id:'alert',memberIds:['m1']})],[event(),event({id:'staff',kind:'staff',at:'2026-10-01T12:01:00Z'}),event({id:'e2',at:'2026-10-01T12:02:00Z'}),event({id:'resume',kind:'resume',at:'2026-10-01T12:03:00Z'}),event({id:'e3',recipientId:'u2',at:'2026-10-01T12:04:00Z'})]);assert.equal(p.actions.filter(a=>a.kind==='reply').length,2);assert.equal(p.actions.find(a=>a.kind==='alert').status,'cancelled');});
test('new customer message replaces unanswered deadline; preview never fires alert jobs',()=>{const p=plan([rule('unanswered_alert',{memberIds:['m1']})],[event(),event({id:'e2',at:'2026-10-01T12:05:00Z'})]);assert.equal(p.actions[0].status,'cancelled');assert.equal(p.actions[1].dueAt,'2026-10-01T12:20:00.000Z');assert.equal(p.executionAvailable,false);});
test('text menu command and exact option produce configurable previews without quick-reply claim',()=>{const r=rule('conversation_menu',{keywords:['menu'],menu:[{label:'Hours',reply:'Tenant hours'}],cooldownMinutes:0});const p=plan([r],[event({text:'menu'}),event({id:'e2',text:'Hours',at:'2026-10-01T12:01:00Z'})]);assert.deepEqual(JSON.parse(JSON.stringify(p.actions.map(a=>a.text))),['Hours','Tenant hours']);});
test('draft module cannot import provider, database or background execution',()=>{const source=require('fs').readFileSync('lib/bot/draft-rules.ts','utf8');assert.doesNotMatch(source,/\b(fetch|setInterval|setTimeout|supabaseAdmin|runAutoReplyBatch)\s*\(/);});
function routeHarness(options={}){const {database}=require('./tenh-seven/harness.cjs');const channel='00000000-0000-4000-8000-000000000001';const db=database({social_accounts:[{id:channel,business_id:options.foreign?'other':'b1',platform:options.platform??'facebook',is_active:true}],team_members:[{id:'m1',business_id:'b1',is_active:true}]});let external=0;const route=loader({'next/server':{NextResponse:Response},'@/lib/supabase/admin':{supabaseAdmin:db},'@/lib/auth/require-permission':{requirePermission:async area=>options.denied||area==='team_members'&&options.teamDenied?{success:false,response:Response.json({error:'denied'},{status:403})}:{success:true,context:{member:{business_id:'b1'},permissions:{channels:'manage'},isOwner:false}}},'@/lib/facebook/auto-reply':{autoReplyGraph:()=>{external++;throw Error('must not send')},inspectAutoReply:()=>{external++;throw Error('must not send')}}})('app/api/facebook/auto-reply/route.ts');return{route,db,channel,external:()=>external};}
async function previewRoute(h,extra={}){return h.route.POST(new Request('https://fixture.test/api/facebook/auto-reply',{method:'POST',body:JSON.stringify({operation:'draftPreview',channelId:h.channel,rules:[rule('keyword_faq',{channelId:h.channel})],events:[event()],now:ctx.now,...extra})}));}
test('real existing API draft operation reads only with zero provider calls',async()=>{const h=routeHarness();const response=await previewRoute(h);assert.equal(response.status,200);assert.equal((await response.json()).executionAvailable,false);assert.equal(h.external(),0);assert.ok(h.db.history.every(q=>q.op==='read'));});
test('API rejects foreign channels, unsupported channels, permission denial and forged scope',async()=>{assert.equal((await previewRoute(routeHarness({foreign:true}))).status,404);assert.equal((await previewRoute(routeHarness({platform:'telegram'}))).status,422);assert.equal((await previewRoute(routeHarness({denied:true}))).status,403);const h=routeHarness();assert.equal((await previewRoute(h,{rules:[rule('keyword_faq',{businessId:'other',channelId:h.channel})]})).status,400);});
test('staff permission denial never exposes or proposes assignment',async()=>{const h=routeHarness({teamDenied:true});const response=await previewRoute(h,{rules:[rule('human_takeover',{channelId:h.channel,memberIds:['m1']})]});assert.equal(response.status,403);assert.equal(h.external(),0);});
