const test=require('node:test'),assert=require('node:assert/strict');const {loader,database}=require('./tenh-seven/harness.cjs');
const api=loader({})('lib/bot/draft-rules.ts');
const ctx={businessId:'b1',channelId:'p1',publicPageId:'123',recordedConnectionStatus:'expired',now:'2026-10-01T12:30:00Z',staff:[]};
const rule=(kind,extra={})=>({id:'r1',kind,businessId:'b1',channelId:'p1',name:'Stage2 fixture',mode:'draft',priority:50,cooldownMinutes:60,keywords:[],template:'Configured reply',awayTemplate:'',timezone:'UTC',hours:[{day:4,start:540,end:1020}],memberIds:[],assignOnIncoming:false,alertMinutes:15,menu:[],...extra});
const event=(extra={})=>({id:'e1',businessId:'b1',channelId:'p1',conversationId:'c1',recipientId:'u1',at:'2026-10-01T12:00:00Z',kind:'customer',text:'quote',...extra});
const comment=extra=>event({kind:'comment',text:'spam +855 12 345 678',comment:{commentId:'123_789',postId:'123_456',parentId:'123_456',deleted:false},...extra});
const seq=extra=>rule('conditional_followups',{keywords:['quote'],options:{steps:[{delayMinutes:120,template:'Configured follow-up'}],cancelKeywords:['stop','cancel'],respectHours:false},...extra});
const plan=(rules,events=[event()],context=ctx)=>api.previewDraftRules(rules,events,context);
const rows=(p,kind)=>p.actions.filter(a=>a.kind===kind);

test('all seven selected kinds exist and every plan remains draft-only',()=>{for(const kind of ['ads_specific_reply','returning_context','connection_health','comment_phone_spam_hide','comment_filters','qr_ref_flow','conditional_followups'])assert(api.DRAFT_KINDS.includes(kind));const p=plan([seq()]);assert.equal(p.executionAvailable,false);assert.equal(p.dryRun,true);assert.match(p.note,/No sends, hides/);});
test('Stage2 requires exact business/channel-scoped events and draft rules',()=>{for(const metadata of [{businessId:'other'},{channelId:'other'},{businessId:undefined,channelId:undefined}])assert.throws(()=>plan([seq()],[event(metadata)]),/scope/i);for(const extra of [{businessId:'other'},{channelId:'other'},{mode:'enabled'}])assert.throws(()=>plan([seq(extra)]));});
test('Ads reply matches only explicit simulated referral IDs, never text or unrelated Ad',()=>{const r=rule('ads_specific_reply',{options:{adIds:['777']}});assert.equal(rows(plan([r],[event({source:{kind:'simulated_ad_referral',adId:'777'}})]),'reply').length,1);assert.equal(plan([r],[event({text:'Ad 777 price'})]).actions.length,0);assert.equal(plan([r],[event({source:{kind:'simulated_ad_referral',adId:'888'}})]).actions.length,0);assert.throws(()=>plan([r],[event({source:{kind:'verified_live',adId:'777'}})]));assert.throws(()=>plan([rule('ads_specific_reply',{options:{adIds:['customer:777']}})]));});
test('Ads replies honor optional keywords, priority, cooldown, bot echo and direct window',()=>{const r=rule('ads_specific_reply',{keywords:['price'],options:{adIds:['777']}}),e=event({text:'price',source:{kind:'simulated_ad_referral',adId:'777'}});assert.equal(rows(plan([r],[e,event({...e,id:'e2',at:'2026-10-01T12:01:00Z'})]),'reply').length,1);assert.equal(rows(plan([r],[{...e,text:'hello'}]),'reply').length,0);assert.equal(rows(plan([r],[{...e,at:'2026-09-30T12:00:00Z'}]),'reply').length,0);assert.throws(()=>plan([r],[{...e,kind:'bot'}]));const higher=rule('keyword_faq',{id:'higher',priority:90,keywords:['price'],template:'Higher'});assert.equal(rows(plan([r,higher],[e]),'reply')[0].text,'Higher');});
test('returning context is synthetic, scoped and bounded; optional reply does not replace history',()=>{const r=rule('returning_context',{options:{minPrevious:2},template:''}),e=event({returning:{previousConversations:2,lastSeenAt:'2026-09-30T12:00:00Z'}});const p=plan([r],[e]);assert.equal(rows(p,'context').length,1);assert.match(p.actions[0].text,/No real customer history/);assert.equal(rows(p,'reply').length,0);assert.equal(plan([r],[event()]).actions.length,0);assert.equal(plan([r],[{...e,returning:{...e.returning,previousConversations:1}}]).actions.length,0);for(const value of [0,10001])assert.throws(()=>plan([r],[{...e,returning:{...e.returning,previousConversations:value}}]));assert.throws(()=>plan([r],[{...e,returning:{...e.returning,lastSeenAt:e.at}}]));});
test('returning replies preserve recipient cooldown across conversations and human/window guards',()=>{const r=rule('returning_context'),e=event({returning:{previousConversations:1,lastSeenAt:'2026-09-30T12:00:00Z'}});assert.equal(rows(plan([r],[e,{...e,id:'e2',conversationId:'c2',at:'2026-10-01T12:01:00Z'}]),'reply').length,1);assert.equal(rows(plan([r],[event({id:'s',kind:'staff',at:'2026-10-01T11:59:00Z'}),e]),'reply').length,0);assert.equal(rows(plan([r],[{...e,at:'2026-10-01T12:00:00Z'}],{...ctx,now:'2026-10-02T12:00:00Z'}),'reply').length,0);});
test('health exposes only server-context normalized metadata and never claims a live probe',()=>{const r=rule('connection_health'),e=event({kind:'health',recordedConnectionStatus:'valid'});const p=plan([r],[e]);assert.match(p.actions[0].text,/expired/);assert.match(p.actions[0].text,/Not a live/);assert.equal(rows(p,'reply').length,0);assert.match(plan([r],[e],{...ctx,recordedConnectionStatus:'private error token'}).actions[0].text,/unknown/);assert(!plan([r],[e],{...ctx,recordedConnectionStatus:'private error token'}).actions[0].text.includes('private'));assert.equal(plan([r],[event()]).actions.length,0);});
test('comment phone hide requires phone pattern plus configured spam, with explicit phone-only opt-in',()=>{const r=rule('comment_phone_spam_hide',{keywords:['spam'],options:{firstLevelOnly:true}});assert.equal(rows(plan([r],[comment()]),'hide_comment').length,1);assert.equal(plan([r],[comment({text:'spam hello'})]).actions.length,0);assert.equal(plan([r],[comment({text:'+855 12 345 678'})]).actions.length,0);assert.equal(rows(plan([rule('comment_phone_spam_hide',{options:{phoneOnly:true}})],[comment({text:'+855 12 345 678'})]),'hide_comment').length,1);assert.throws(()=>plan([rule('comment_phone_spam_hide')],[comment()]));assert(!JSON.stringify(plan([r],[comment()]).actions).includes('855'));});
test('comment hide respects deleted/nested/unknown parent, exclusions and foreign public Page',()=>{const r=rule('comment_phone_spam_hide',{keywords:['spam'],options:{firstLevelOnly:true,excludeKeywords:['support']}}),e=comment();for(const parentId of [null,'123_999'])assert.equal(plan([r],[{...e,comment:{...e.comment,parentId}}]).actions.length,0);assert.equal(plan([r],[{...e,comment:{...e.comment,deleted:true}}]).actions.length,0);assert.equal(plan([r],[{...e,text:'support spam +855 12 345 678'}]).actions.length,0);assert.throws(()=>plan([r],[{...e,comment:{...e.comment,postId:'999_456',parentId:'999_456'}}]),/selected public Page/);assert.throws(()=>plan([r],[{...e,kind:'customer'}]),/Comment metadata/);});
test('comment filters include/exclude Unicode literal keywords and first-level evidence',()=>{const r=rule('comment_filters',{keywords:['offer'],options:{excludeKeywords:['SPAM'],firstLevelOnly:true}});const e=comment({text:'ＯＦＦＥＲ'});assert.match(rows(plan([r],[e]),'filter')[0].text,/Include/);assert.match(rows(plan([r],[{...e,text:'offer spam'}]),'filter')[0].text,/Exclude/);assert.match(rows(plan([r],[{...e,comment:{...e.comment,parentId:null}}]),'filter')[0].reason,/not proven/);assert.equal(rows(plan([r],[event({text:'offer'})]),'filter').length,0);});
test('cooled-down filter still constrains hide proposals and comments never propose direct replies',()=>{const filter=rule('comment_filters',{keywords:[],options:{excludeKeywords:['support']}}),hide=rule('comment_phone_spam_hide',{id:'hide',keywords:['spam'],cooldownMinutes:0}),e=comment({text:'spam +855 12 345 678'});const p=plan([filter,hide],[e,{...e,id:'e2',at:'2026-10-01T12:01:00Z',text:'support spam +855 12 345 678'}]);assert.equal(rows(p,'hide_comment').length,1);assert.equal(rows(p,'filter').length,1);assert.equal(rows(p,'reply').length,0);});
test('referral flow produces only selected public Page and static public campaign QR payload',()=>{const r=rule('qr_ref_flow',{options:{refToken:'campaign_summer'}}),e=event({kind:'referral',refToken:'campaign_summer'}),p=plan([r],[e]);assert.equal(p.actions[0].url,'https://m.me/123?ref=campaign_summer');assert.equal(rows(p,'reply').length,0);assert.equal(plan([r],[{...e,refToken:'campaign_winter'}]).actions.length,0);assert.throws(()=>plan([r],[e],{...ctx,publicPageId:'foreign/path'}));assert.equal(api.draftFlowUrl('123','campaign_summer'),'https://m.me/123?ref=campaign_summer');});
test('QR/reference token rejects URLs, redirects, personal IDs, email, phone and secret-shaped labels',()=>{for(const value of ['https://evil.test','campaign_123456789','campaign_customer','campaign_secret','campaign_a@b','campaign_summer?redirect=x','campaign_summer#x','campaign_summer%2fsecret','campaign_token'])assert.throws(()=>plan([rule('qr_ref_flow',{options:{refToken:value}})]));for(const value of ['https://m.me/123','123@evil.test','123/../456'])assert.throws(()=>api.draftFlowUrl(value,'campaign_summer'));});
test('direct QR entry reply still requires exact ref and direct window; referral cannot open follow-ups',()=>{const r=rule('qr_ref_flow',{options:{refToken:'campaign_summer'}}),e=event({refToken:'campaign_summer'});assert.equal(rows(plan([r],[e]),'reply').length,1);assert.equal(rows(plan([r],[{...e,at:'2026-09-30T12:00:00Z'}]),'reply').length,0);assert.equal(rows(plan([seq()],[event({kind:'referral',refToken:'campaign_summer'})]),'followup').length,0);});
test('conditional follow-ups are bounded cumulative prospective steps, no scheduler execution',()=>{const p=plan([seq({options:{steps:[{delayMinutes:120,template:'One'},{delayMinutes:60,template:'Two'}],cancelKeywords:['stop'],respectHours:false}})]);assert.deepEqual(JSON.parse(JSON.stringify(p.actions.map(a=>[a.text,a.dueAt,a.status]))),[['One','2026-10-01T14:00:00.000Z','proposed'],['Two','2026-10-01T15:00:00.000Z','proposed']]);assert.equal(new Set(p.actions.map(a=>a.key)).size,2);assert.equal(plan([seq()],[event({text:'unmatched'})]).actions.length,0);});
for(const kind of ['customer','staff','cancel'])test('pending sequence cancellation on '+kind+' is stable out of order and duplicate delivery',()=>{const later=event({id:'later',kind,text:'answer',at:'2026-10-01T12:10:00Z'}),e=event(),p=plan([seq()],[later,e,e,later]);assert.equal(rows(p,'followup').length,1);assert.equal(p.actions[0].status,'cancelled');});
test('customer cancel keywords stop plans without restarting and contact reply in another conversation cancels',()=>{const r=seq({keywords:['quote','cancel']}),e=event();assert.equal(rows(plan([r],[e,event({id:'stop',text:'cancel quote',at:'2026-10-01T12:10:00Z'})]),'followup').length,1);assert.equal(plan([r],[e,event({id:'stop',text:'cancel quote',at:'2026-10-01T12:10:00Z'})]).actions[0].status,'cancelled');assert.equal(plan([seq()],[e,event({id:'other',conversationId:'c2',text:'hello',at:'2026-10-01T12:10:00Z'})]).actions[0].status,'cancelled');});
test('same-time staff takeover/operator cancellation preempts prospective follow-ups deterministically',()=>{assert.equal(rows(plan([seq()],[event(),event({id:'z',kind:'staff'})]),'followup').length,0);assert.equal(rows(plan([seq()],[event(),event({id:'z',kind:'cancel'})]),'followup').length,0);});
test('human takeover preempts followups and explicit resume never resurrects a cancelled sequence',()=>{const c={...ctx,staff:[{id:'m1',load:0}]},takeover=rule('human_takeover',{id:'human',keywords:['quote'],memberIds:['m1']});assert.equal(rows(plan([seq(),takeover],[event()],c),'followup').length,0);const p=plan([seq()],[event(),event({id:'staff',kind:'staff',at:'2026-10-01T12:05:00Z'}),event({id:'resume',kind:'resume',at:'2026-10-01T12:10:00Z'})]);assert.equal(p.actions[0].status,'cancelled');});
test('expired/boundary/past-due steps are skipped; comment and bot echoes cannot schedule',()=>{const r=seq({options:{steps:[{delayMinutes:10,template:'Old'},{delayMinutes:1430,template:'Boundary'}],cancelKeywords:['stop']}}),p=plan([r]);assert.deepEqual(JSON.parse(JSON.stringify(p.actions.map(a=>a.status))),['skipped','skipped']);assert.match(p.actions[0].reason,/never backfill/);assert.match(p.actions[1].reason,/24-hour/);assert.equal(plan([seq()],[event({at:'2026-09-30T12:00:00Z'})]).actions.length,0);assert.equal(plan([seq()],[event({kind:'bot'})]).actions.length,0);assert.equal(rows(plan([seq()],[comment({text:'quote'})]),'followup').length,0);});
test('follow-up timezone hours skip rather than silently delay, including DST repeated hour',()=>{const r=seq({timezone:'Asia/Phnom_Penh',options:{steps:[{delayMinutes:120,template:'Hours'}],cancelKeywords:['stop'],respectHours:true}});assert.equal(plan([r]).actions[0].status,'skipped');assert.match(plan([r]).actions[0].reason,/timezone/);const ny=seq({timezone:'America/New_York',hours:[{day:0,start:60,end:120}],options:{steps:[{delayMinutes:60,template:'DST'}],cancelKeywords:['stop'],respectHours:true}});assert.equal(plan([ny],[event({at:'2026-11-01T05:30:00Z'})],{...ctx,now:'2026-11-01T05:31:00Z'}).actions[0].status,'proposed');});
test('steps/cancel/trigger/hour contracts and unknown options fail closed',()=>{for(const options of [{steps:[],cancelKeywords:['stop']},{steps:Array.from({length:6},()=>({delayMinutes:1,template:'a'})),cancelKeywords:['stop']},{steps:[{delayMinutes:0,template:'a'}],cancelKeywords:['stop']},{steps:[{delayMinutes:1441,template:'a'}],cancelKeywords:['stop']},{steps:[{delayMinutes:1,template:'a'}],cancelKeywords:[]},{liveUrl:'https://evil.test'}])assert.throws(()=>plan([seq({options})]));assert.throws(()=>plan([seq({keywords:[]})]));assert.throws(()=>plan([seq({hours:[],options:{steps:[{delayMinutes:60,template:'a'}],cancelKeywords:['stop'],respectHours:true}})]));});
test('conflicting event IDs reject instead of silently choosing a customer identity',()=>{assert.throws(()=>plan([seq()],[event(),event({recipientId:'foreign'})]),/Conflicting duplicate/);});
test('proposal budget rejects oversized health plans rather than silently dropping actions',()=>{const rules=Array.from({length:20},(_,i)=>rule('connection_health',{id:'r'+i,cooldownMinutes:0})),events=Array.from({length:30},(_,i)=>event({id:'e'+i,kind:'health'}));assert.throws(()=>plan(rules,events),/500 items/);});
function routeHarness({foreign=false,denied=false,platform='facebook'}={}){const channel='00000000-0000-4000-8000-000000000001';const db=database({social_accounts:[{id:channel,business_id:foreign?'other':'b1',platform,platform_account_id:'123',facebook_token_status:'expired',is_active:true}],team_members:[]});let provider=0;const route=loader({'next/server':{NextResponse:Response},'@/lib/supabase/admin':{supabaseAdmin:db},'@/lib/auth/require-permission':{requirePermission:async()=>denied?{success:false,response:Response.json({error:'denied'},{status:403})}:{success:true,context:{member:{business_id:'b1'},permissions:{channels:'manage'},isOwner:false}}},'@/lib/facebook/auto-reply':{autoReplyGraph:()=>{provider++;throw Error('No provider')},inspectAutoReply:()=>{provider++;throw Error('No provider')}}})('app/api/facebook/auto-reply/route.ts');return {channel,db,route,provider:()=>provider};}
const request=(h,r,e,extra={})=>new Request('https://fixture.test/api/facebook/auto-reply',{method:'POST',body:JSON.stringify({operation:'draftPreview',channelId:h.channel,now:ctx.now,rules:[{...r,channelId:h.channel}],events:e.map(x=>({...x,channelId:h.channel})),...extra})});
test('real API Stage2 ignores forged health/Page metadata, reads only selected tenant channel, never provider',async()=>{const h=routeHarness(),response=await h.route.POST(request(h,rule('connection_health'),[event({kind:'health'})],{publicPageId:'999',recordedConnectionStatus:'valid'})),body=await response.json();assert.equal(response.status,200);assert.match(body.actions[0].text,/expired/);assert.equal(h.provider(),0);assert(h.db.history.every(q=>q.op==='read'));const r=await h.route.POST(request(h,rule('qr_ref_flow',{options:{refToken:'campaign_summer'}}),[event({kind:'referral',refToken:'campaign_summer'})],{publicPageId:'999'}));assert.equal((await r.json()).actions[0].url,'https://m.me/123?ref=campaign_summer');});
test('real API rejects tenant/channel/permission/platform failures and forged synthetic event scope',async()=>{for(const [options,status] of [[{foreign:true},404],[{denied:true},403],[{platform:'telegram'},422]]){const h=routeHarness(options);assert.equal((await h.route.POST(request(h,seq(),[event()]))).status,status);assert.equal(h.provider(),0);}const h=routeHarness();assert.equal((await h.route.POST(request(h,seq(),[event({businessId:'foreign'})]))).status,400);assert.equal((await h.route.POST(request(h,rule('comment_phone_spam_hide',{keywords:['spam']}),[comment({comment:{commentId:'999_789',postId:'999_456',parentId:'999_456',deleted:false}})]))).status,400);assert(h.db.history.every(q=>q.op==='read'));});

test('repeated callbacks for the same comment do not duplicate hide proposals',()=>{const r=rule('comment_phone_spam_hide',{keywords:['spam'],cooldownMinutes:0}),e=comment();assert.equal(rows(plan([r],[e,{...e,id:'repeat',at:'2026-10-01T12:01:00Z'}]),'hide_comment').length,1);});
test('scoped GET draft context returns only public Page/normalized health metadata, never tokens',async()=>{const h=routeHarness();h.db.tables.social_accounts[0].facebook_page_access_token_encrypted='fixture-private-token';const response=await h.route.GET({nextUrl:new URL('https://fixture.test/api/facebook/auto-reply?scope=drafts')}),body=await response.json();assert.equal(response.status,200);assert.equal(body.pages[0].platform_account_id,'123');assert.equal(body.pages[0].recordedConnectionStatus,'expired');assert(!JSON.stringify(body).includes('fixture-private-token'));assert(h.db.history.every(q=>q.op==='read'));assert.equal(h.provider(),0);});

test('duplicate delivery is independent of JSON field order',()=>{const e=event(),reordered=Object.fromEntries(Object.entries(e).reverse());assert.equal(rows(plan([seq()],[e,reordered]),'followup').length,1);});

test('cancellation and human holds stay scoped to the synthetic recipient',()=>{const one=event(),two=event({id:'two',recipientId:'u2'}),cancel=event({id:'cancel-two',recipientId:'u2',kind:'staff',at:'2026-10-01T12:10:00Z'}),p=plan([seq()],[one,two,cancel]);assert.equal(p.actions.find(a=>a.recipientId==='u1').status,'proposed');assert.equal(p.actions.find(a=>a.recipientId==='u2').status,'cancelled');});

test('validated timezone whitespace is normalized consistently before follow-up hour checks',()=>{const r=seq({timezone:' UTC ',options:{steps:[{delayMinutes:120,template:'Hours'}],cancelKeywords:['stop'],respectHours:true}}),parsed=api.parseDraftRules([r],ctx)[0];assert.equal(parsed.timezone,'UTC');assert.equal(plan([r]).actions[0].status,'proposed');});
