const test=require('node:test'),assert=require('node:assert/strict'),React=require('react'),{act}=React,{createRoot}=require('react-dom/client'),{JSDOM}=require('jsdom'),{loader}=require('./tenh-seven/harness.cjs');
async function setup(t){const dom=new JSDOM('<div id="root"></div>',{url:'https://fixture.test/dashboard/tenh-bot'});global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;const load=loader({react:React,'react/jsx-runtime':require('react/jsx-runtime')},{window:dom.window,document:dom.window.document}),module=load('components/bot/bot-save-toolbar.tsx'),root=createRoot(document.getElementById('root'));t.after(async()=>{await act(async()=>root.unmount());dom.window.close()});return {...module,root,dom};}
test('shared save reports partial persistence precisely and retries only the unsaved model',async t=>{const h=await setup(t),calls=[];let commentsOk=false;
 function Editor({slot}){const [dirty,setDirty]=React.useState(true);h.useBotSaveRegistration(slot,{dirty,busy:false,canSave:true,message:''},async()=>{calls.push(slot);const ok=slot==='modern'||commentsOk;if(ok)setDirty(false);return {ok,message:ok?'Saved disabled.':'Comment storage conflict.'}});return React.createElement('p',{'data-slot':slot},dirty?'Unsaved':'Saved')}
 const render=()=>h.root.render(React.createElement(h.BotSaveWorkspace,null,React.createElement(Editor,{slot:'modern'}),React.createElement(Editor,{slot:'comments'})));
 await act(async()=>render());await act(async()=>document.querySelector('button').click());assert.deepEqual(calls,['modern','comments']);assert.match(document.querySelector('[role=alert]').textContent,/Page Bot rules saved.*Comment storage conflict.*retained/);assert.equal(document.querySelector('[data-slot=modern]').textContent,'Saved');assert.equal(document.querySelector('[data-slot=comments]').textContent,'Unsaved');
 commentsOk=true;await act(async()=>document.querySelector('button').click());assert.deepEqual(calls,['modern','comments','comments']);assert.equal(document.querySelector('[role=alert]'),null);assert.equal(document.querySelector('button').disabled,true);
});
test('permission or unfinished-form blockers prevent saves and protect normal in-app navigation',async t=>{const h=await setup(t);let calls=0;window.confirm=()=>false;
 function Editor(){h.useBotSaveRegistration('modern',{dirty:true,busy:false,canSave:false,message:'Add unfinished form edits before saving.'},async()=>{calls++;return {ok:true,message:'Saved'}});return React.createElement('a',{href:'/dashboard/analytics'},'Analytics')}
 await act(async()=>h.root.render(React.createElement(h.BotSaveWorkspace,null,React.createElement(Editor))));assert.equal(document.querySelector('button').disabled,true);assert.match(document.querySelector('[role=status]').textContent,/unfinished/);await act(async()=>document.querySelector('button').click());assert.equal(calls,0);const event=new window.MouseEvent('click',{bubbles:true,cancelable:true,button:0});document.querySelector('a').dispatchEvent(event);assert.equal(event.defaultPrevented,true);
});
test('concurrent clicks run one command and preserve dirty work on failure',async t=>{const h=await setup(t);let calls=0,release;
 function Editor(){h.useBotSaveRegistration('modern',{dirty:true,busy:false,canSave:true,message:''},()=>{calls++;return new Promise(resolve=>release=resolve)});return null}
 await act(async()=>h.root.render(React.createElement(h.BotSaveWorkspace,null,React.createElement(Editor))));await act(async()=>{const button=document.querySelector('button');button.click();button.click()});assert.equal(calls,1);assert.equal(document.querySelector('button').disabled,true);await act(async()=>release({ok:false,message:'Revision conflict.'}));assert.match(document.querySelector('[role=alert]').textContent,/Revision conflict.*retained/);assert.equal(document.querySelector('button').disabled,false);
});
