const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
const {loader,database,baseSeed}=require('./tenh-seven/harness.cjs');
const clone=x=>JSON.parse(JSON.stringify(x));
const guard=loader({'@/lib/supabase/admin':{supabaseAdmin:{}}})('lib/facebook/send-reply-context.ts').requireFacebookReplyWindow;
for(const state of ['standard','human_agent'])test(`manual text quote accepts eligible ${state}`,()=>assert.doesNotThrow(()=>guard({},state,{allowHumanAgentText:true})));
for(const state of ['expired','unknown','waiting_for_customer_reply','private_reply_available'])test(`manual text quote retains closed ${state} restriction`,()=>assert.throws(()=>guard({},state,{allowHumanAgentText:true}),e=>e.status===409));
test('attachment callers retain standard-only quoted restriction',()=>{assert.doesNotThrow(()=>guard({},'standard'));assert.throws(()=>guard({},'human_agent'),e=>e.status===409);assert.doesNotThrow(()=>guard(null,'human_agent'));});

function server({state='human_agent',failure,denied=false,policyFailure=false}={}){
 const seed=baseSeed();seed.messages.push({id:'quote',business_id:'b1',conversation_id:'conv1',platform_message_id:'incoming-mid',direction:'incoming',message_type:'text',message_text:'Question',raw_payload:{message:{mid:'incoming-mid'}}});
 const db=database(seed),calls=[];
 const load=loader({
  '@/lib/supabase/admin':{supabaseAdmin:db},
  '@/lib/inbox/get-inbox-resource-access':{getInboxConversationAccess:async()=>({success:true,member:{id:'m1',business_id:'b1'}})},
  '@/lib/auth/require-permission':{memberHasPermission:async()=>!denied,permissionDenied:error=>Response.json({success:false,error},{status:403})},
  '@/lib/facebook/customer-block':{facebookSendBlockReason:async()=>null},
  '@/lib/facebook/get-facebook-page-access-token':{getFacebookPageAccessToken:async()=> 'FAKE_TOKEN',isFacebookAccessTokenError:()=>false},
  '@/lib/facebook/messenger-reply-policy':{getFacebookMessengerReplyPolicy:async()=>{if(policyFailure)throw Error('Fixture policy unavailable');return {windowState:state,hasRecentDirectCustomerMessage:state==='standard',latestDirectIncomingAt:'2026-10-01T00:00:00Z',latestIncomingCommentId:'post_comment'}}},
  '@/lib/inbox/mutate-message-metadata':{mutateMessageMetadata:async()=>{}},
 },{console:{warn(){},error(){}},fetch:async(url,init)=>{calls.push(clone(JSON.parse(init.body)));if(failure==='network')throw Error('Fixture network interrupted');if(failure==='invalid')return new Response('invalid',{status:502});if(failure==='missing-id')return Response.json({recipient_id:'100076611888104'});if(failure==='rejected')return Response.json({error:{code:100,message:'Unsupported quoted support payload'}},{status:400});return Response.json({message_id:'outgoing-mid',recipient_id:'100076611888104'});}});
 const post=load('app/api/facebook/send/route.ts').POST;
 return {db,calls,send:(overrides={})=>post({json:async()=>({conversationId:'conv1',recipientId:'100076611888104',message:'Support answer',replyToMessageId:'quote',...overrides})})};
}
for(const state of ['standard','human_agent'])test(`real text route preserves quote and ${state} payload mode`,async()=>{
 const app=server({state}),r=await app.send();assert.equal(r.status,200);assert.equal(app.calls.length,1);const body=app.calls[0];assert.deepEqual(body.reply_to,{mid:'incoming-mid'});assert.equal(body.message.text,'Support answer');assert.equal(body.messaging_type,state==='standard'?'RESPONSE':'MESSAGE_TAG');assert.equal(body.tag,state==='standard'?undefined:'HUMAN_AGENT');assert.equal(app.db.tables.messages.filter(m=>m.platform_message_id==='outgoing-mid').length,1);
});
for(const state of ['expired','unknown','waiting_for_customer_reply','private_reply_available'])test(`real route ${state} never sends a quoted support message`,async()=>{const app=server({state});assert.equal((await app.send()).status,409);assert.equal(app.calls.length,0);});
test('permission and policy inspection failures never send',async()=>{for(const options of [{denied:true},{policyFailure:true}]){const app=server(options);assert.ok((await app.send()).status>=400);assert.equal(app.calls.length,0);}});
test('quote target must remain in the authorized conversation',async()=>{const app=server();app.db.tables.messages[0].conversation_id='other';assert.equal((await app.send()).status,400);assert.equal(app.calls.length,0);});
test('Meta explicit rejection is authoritative with no quote dropping or second send',async()=>{const app=server({failure:'rejected'}),r=await app.send(),body=await r.json();assert.equal(r.status,400);assert.equal(body.code,'FACEBOOK_QUOTED_REPLY_REJECTED');assert.match(body.error,/Unsupported quoted support payload/);assert.equal(app.calls.length,1);assert.equal(app.calls[0].tag,'HUMAN_AGENT');assert.deepEqual(app.calls[0].reply_to,{mid:'incoming-mid'});assert.equal(app.db.history.filter(x=>x.op!=='read').length,0);});
for(const failure of ['network','invalid','missing-id'])test(`uncertain ${failure} response is not automatically resent`,async()=>{const app=server({failure});assert.equal((await app.send()).status,502);assert.equal(app.calls.length,1);assert.equal(app.db.history.filter(x=>x.op!=='read').length,0);});

function client({outcome='rejected',duringFlight,quoted=true}={}){
 const source=fs.readFileSync('components/inbox/inbox-view.tsx','utf8'),ast=ts.createSourceFile('inbox.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
 const names=new Set(['performOptimisticSend','handleSendMessage','handleRetryOptimisticMessage']);let functions=[];function visit(n){if(ts.isFunctionDeclaration(n)&&names.has(n.name?.text))functions.push(n.getText(ast));ts.forEachChild(n,visit)}visit(ast);assert.equal(functions.length,3);
 const actions=loader()('lib/inbox/message-actions.ts'),quote={id:'quote',conversation_id:'conv1',platform_message_id:'incoming-mid',message_type:'text',direction:'incoming',message_text:'Question'};
 const conversation={id:'conv1',contact:{platform_user_id:'customer'}},state={draft:'Support answer',quote:quoted?'quote':null,messages:[quote],calls:[],statuses:[],error:null},pending={current:{}};
 const draftRef={current:{reply:state.draft,quote:state.quote,revision:0}};
 const assign=(key,value)=>{const next=typeof value==='function'?value(key==='reply'?state.draft:state.quote):value;const old=draftRef.current[key];if(next!==old)draftRef.current.revision++;draftRef.current[key]=next;state[key==='reply'?'draft':'quote']=next;};
 const context={...actions,console,Response,crypto:{randomUUID:()=> 'fixture'},reply:state.draft,activeConversation:conversation,activeConversationRef:{current:conversation},desiredConversationIdRef:{current:'conv1'},replyingToCommentId:null,replyingToTelegramMessageId:null,replyingToFacebookMessageId:'quote',editingTelegramMessageId:null,liveMessagesRef:{current:state.messages},pendingSendsRef:pending,
  resolveConversationPlatform:async()=> 'facebook',createOptimisticMessage:({tempId,conversationId,message})=>({id:tempId,conversation_id:conversationId,message_text:message,created_at:'2026-10-01T00:00:00Z'}),updateConversationPreviewOptimistically(){},
  setLiveMessages:fn=>state.messages=fn(state.messages),setSending:v=>state.sending=v,setSendError:v=>state.error=v,setOptimisticSendStatus:(id,status)=>state.statuses.push(status),confirmOutgoingMessage:rows=>rows,isDeletedCommentError:()=>false,
  composerDraftRef:draftRef,textSubmissionsRef:{current:new Set()},latestTextSubmissionRef:{current:0},
  conversationMessageCacheRef:{current:{conv1:{messages:[],hasMore:false,fetchedAt:0}}},setCachedConversationPage:(id,page)=>context.conversationMessageCacheRef.current[id]=page,
  setReply:v=>assign('reply',v),setReplyingToFacebookMessageId:v=>assign('quote',v),setReplyingToCommentId(){},setReplyingToTelegramMessageId(){},setEditingTelegramMessageId(){},
  fetch:async(url,init)=>{state.calls.push(clone(JSON.parse(init.body)));await duringFlight?.(state,context);if(outcome==='network')throw Error('Network interrupted; check delivery before resending');return Response.json(outcome==='success'?{success:true,messageId:'outgoing-mid'}:{success:false,code:'FACEBOOK_QUOTED_REPLY_REJECTED',error:'Meta rejected this quoted support reply.'},{status:outcome==='success'?200:400});},
 };
 context.replyingToFacebookMessageId=state.quote;
 context.pendingAttachmentSendsRef={current:{}};
 vm.createContext(context);vm.runInContext(ts.transpileModule(functions.join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);
 return {state,pending,context,send:()=>context.handleSendMessage({preventDefault(){}}),retry:()=>context.handleRetryOptimisticMessage('optimistic:fixture')};
}
test('actual client rejection preserves draft/quote and removes duplicate Retry copy',async()=>{const app=client();await app.send();assert.equal(app.state.draft,'Support answer');assert.equal(app.state.quote,'quote');assert.equal(app.state.calls.length,1);assert.equal(app.state.calls[0].replyToMessageId,'quote');assert.equal(app.state.messages.length,1);assert.equal(Object.keys(app.pending.current).length,0);assert.match(app.state.error,/Meta rejected/);});
test('actual quoted client immediately moves draft/context into sending bubble',async()=>{let cleared=false;const app=client({outcome:'success',duringFlight:s=>{cleared=s.draft===''&&s.quote===null;assert.equal(s.messages.at(-1).raw_payload.tenh_reply.preview_text,'Question');}});await app.send();assert.equal(cleared,true);assert.equal(app.state.draft,'');assert.equal(app.state.quote,null);assert.equal(app.state.calls.length,1);});
test('success does not erase an edited draft/new quote or another conversation',async()=>{for(const switchConversation of [false,true]){const app=client({outcome:'success',duringFlight:(s,c)=>{c.setReply('New draft');c.setReplyingToFacebookMessageId('new-quote');if(switchConversation)c.desiredConversationIdRef.current='other';}});await app.send();assert.equal(app.state.draft,'New draft');assert.equal(app.state.quote,'new-quote');assert.equal(app.state.calls.length,1);}});

test('failed recovery never overwrites newer typing or quote; rejected bubble retains original context',async()=>{for(const outcome of ['rejected','network']){const app=client({outcome,duringFlight:(s,c)=>{c.setReply('New draft');c.setReplyingToFacebookMessageId('new-quote');}});await app.send();assert.equal(app.state.draft,'New draft');assert.equal(app.state.quote,'new-quote');assert.equal(app.state.messages.at(-1).raw_payload.tenh_reply.preview_text,'Question');assert.equal(app.state.calls.length,1);}});
test('failure after conversation switch never restores into another composer and retains failed request in original thread cache',async()=>{const app=client({duringFlight:(s,c)=>{c.desiredConversationIdRef.current='other';}});await app.send();assert.equal(app.state.draft,'');assert.equal(app.state.quote,null);assert.equal(app.state.calls.length,1);assert.equal(app.state.messages.length,1);assert.equal(app.context.conversationMessageCacheRef.current.conv1.messages[0].raw_payload.tenh_reply.preview_text,'Question');});
test('typing then intentionally clearing is newer work and does not restore an older failed draft',async()=>{const app=client({duringFlight:(s,c)=>{c.setReply('Changed');c.setReply('');}});await app.send();assert.equal(app.state.draft,'');assert.equal(app.state.quote,null);assert.equal(app.state.messages.at(-1).__optimistic_status,'failed');});
test('identical overlapping submission is blocked before another optimistic bubble or send',async()=>{let release;const app=client({outcome:'success',duringFlight:()=>new Promise(r=>release=r)});const first=app.send();await new Promise(r=>setImmediate(r));await app.send();assert.equal(app.state.calls.length,1);assert.equal(app.state.messages.length,2);release();await first;});
test('new independent draft can submit while previous quoted send remains pending',async()=>{let release,count=0;const app=client({outcome:'success',duringFlight:()=>++count===1?new Promise(r=>release=r):undefined});const first=app.send();await new Promise(r=>setImmediate(r));app.context.setReply('New independent answer');app.context.reply='New independent answer';app.context.replyingToFacebookMessageId=null;await app.send();assert.equal(app.state.calls.length,2);release();await first;assert.equal(app.state.draft,'');});
test('normal unquoted chat still clears immediately without quote recovery',async()=>{const app=client({quoted:false,outcome:'success',duringFlight:s=>assert.equal(s.draft,'')});await app.send();assert.equal(app.state.calls.length,1);assert.equal(app.state.calls[0].replyToMessageId,undefined);assert.equal(app.state.draft,'');});
test('actual client uncertain failure retains context and forbids Retry of uncertain delivery',async()=>{const app=client({outcome:'network'});await app.send();assert.equal(app.state.calls.length,1);assert.equal(app.state.draft,'Support answer');assert.equal(app.state.quote,'quote');assert.equal(app.state.statuses.at(-1),'failed');assert.equal(app.state.messages.at(-1).__optimistic_requires_review,true);await app.retry();assert.equal(app.state.calls.length,1);assert.match(app.state.error,/Check Messenger/);});
