const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript'),vm=require('vm');
const {loader}=require('./tenh-seven/harness.cjs');
const load=loader(),{retainLocalImagePreview,localImagePreview}=load('lib/inbox/local-image-preview.ts'),{normalizeMessages}=load('lib/inbox/normalize-messages.ts'),{withOptimisticRenderKey}=load('lib/inbox/confirm-outgoing-message.ts');
const row=(patch={})=>({id:'stored',business_id:'b1',conversation_id:'c1',platform_message_id:'mid',direction:'outgoing',message_type:'image',attachment_url:'/saved/image',raw_payload:{},delivery_status:'sent',...patch});
test('saved URL remains authoritative while local preview survives echoes and reopened cached history',()=>{const local=row({id:'optimistic:one',attachment_url:'blob:local'}),saved=retainLocalImagePreview(row(),local);assert.equal(saved.attachment_url,'/saved/image');assert.equal(localImagePreview(saved),'blob:local');const echo=normalizeMessages([row({delivery_status:'seen'})],[saved])[0];assert.equal(echo.attachment_url,'/saved/image');assert.equal(echo.delivery_status,'seen');assert.equal(localImagePreview(echo),'blob:local');const reopened=normalizeMessages([row()],[echo])[0];assert.equal(localImagePreview(reopened),'blob:local');});
test('partial album indices preserve exact local photo instead of showing photo zero',()=>{const local=row({id:'optimistic:album',attachment_url:'blob:zero',raw_payload:{message:{attachments:['zero','one','two'].map(name=>({type:'image',payload:{url:'blob:'+name}}))}}});const saved=retainLocalImagePreview(row({raw_payload:{tenh_image_album:{saved_indices:[0,2]},message:{attachments:[{type:'image',payload:{url:'/saved/0'}},{type:'image',payload:{url:'/saved/2'}}]}}}),local);assert.equal(localImagePreview({...saved,id:'stored:photo:0'}),'blob:zero');assert.equal(localImagePreview({...saved,id:'stored:photo:1'}),'blob:two');assert.equal(saved.raw_payload.message.attachments[1].payload.url,'/saved/2');const echo=normalizeMessages([row()],[saved])[0];assert.equal(localImagePreview({...echo,id:'stored:photo:1'}),'blob:two');});
test('preview never crosses workspace, conversation, provider identity, incoming messages or deletion',()=>{const local=row({id:'optimistic:one',attachment_url:'blob:local'});for(const patch of [{business_id:'other'},{conversation_id:'other'},{direction:'incoming'},{message_type:'video'}])assert.equal(localImagePreview(retainLocalImagePreview(row(patch),local)),undefined);assert.equal(localImagePreview(retainLocalImagePreview(row({platform_message_id:'other'}),row({attachment_url:'blob:local'}))),undefined);const preview=retainLocalImagePreview(row(),local);assert.equal(localImagePreview(retainLocalImagePreview({...preview,raw_payload:{tenh_deleted:{}}},preview)),undefined);});
test('actual optimistic reconciliation keeps canonical URL, local preview and existing sent identity',()=>{const source=fs.readFileSync('components/inbox/inbox-view.tsx','utf8'),ast=ts.createSourceFile('view.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let fn;function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text==='reconcileOptimisticMessage')fn=n.getText(ast);ts.forEachChild(n,visit);}visit(ast);const context={retainLocalImagePreview,withOptimisticRenderKey,Date};vm.createContext(context);vm.runInContext(ts.transpileModule(fn,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);const local=row({id:'optimistic:one',attachment_url:'blob:local'});for(const current of [[local],[local,row({delivery_status:'seen'})]]){const rows=context.reconcileOptimisticMessage(current,'optimistic:one',row(),'blob:local');assert.equal(rows.length,1);assert.equal(rows[0].id,'stored');assert.equal(rows[0].attachment_url,'/saved/image');assert.equal(localImagePreview(rows[0]),'blob:local');}});

const {JSDOM}=require('jsdom'),React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
const component=loader({react:React,'react/jsx-runtime':require('react/jsx-runtime')},{URLSearchParams})('components/inbox/inbox-photo-image.tsx').InboxPhotoImage;
async function mount(t,patch={}){const dom=new JSDOM('<div id="root"></div>');global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;let opens=0;const root=createRoot(document.getElementById('root'));const props={src:'/saved/'+Math.random(),alt:'Fixture photo',className:'test-image',layout:'single',onOpen:()=>opens++,...patch};const render=async changes=>act(async()=>root.render(React.createElement(component,{...props,...changes})));await render();t.after(async()=>{await act(async()=>root.unmount());dom.window.close();});return {render,opens:()=>opens,event:async type=>act(async()=>document.querySelector('img').dispatchEvent(new window.Event(type,{bubbles:true})))};}
test('slow single load has reserved geometry, lazy decoding and accessible status until loaded',async t=>{const a=await mount(t);assert.equal(document.querySelector('[data-photo-state]').style.aspectRatio,'4 / 3');assert.ok(document.querySelector('[role="status"]'));assert.equal(document.querySelector('img').getAttribute('loading'),'lazy');assert.equal(document.querySelector('img').getAttribute('decoding'),'async');await a.event('load');assert.equal(document.querySelector('[data-photo-state]').dataset.photoState,'loaded');assert.equal(document.querySelector('[role="status"]'),null);assert.equal(document.querySelector('[data-photo-state]').style.aspectRatio,'4 / 3');});
test('local preview stays selected across remote URL changes without remounting image',async t=>{const a=await mount(t,{previewSrc:'blob:preferred'});const before=document.querySelector('img');assert.equal(before.getAttribute('src'),'blob:preferred');await a.event('load');await a.render({src:'/new-signed-url'});assert.equal(document.querySelector('img'),before);assert.equal(before.getAttribute('src'),'blob:preferred');assert.equal(document.querySelector('[role="status"]'),null);});
test('expired selected album photo gets one exact-index thumbnail recovery then accessible manual retry',async t=>{const a=await mount(t,{reference:{conversationId:'c1',messageId:'stored:photo:2'},layout:'fill'});await a.event('error');const recovered=new URL(document.querySelector('img').getAttribute('src'),'http://local');assert.equal(recovered.searchParams.get('photoIndex'),'2');assert.equal(recovered.searchParams.get('thumbnail'),'1');await a.event('error');assert.equal(document.querySelector('img'),null);assert.match(document.querySelector('[role="img"]').getAttribute('aria-label'),/Photo unavailable/);assert.equal(document.querySelector('button button'),null);await act(async()=>document.querySelector('button').click());assert.ok(document.querySelector('img'));assert.equal(a.opens(),0);assert.equal(document.querySelector('[data-photo-state]').style.minHeight,'64px');});
test('optimistic image failures do not request an unresolved temporary server message',async t=>{const a=await mount(t,{src:'blob:unavailable',reference:{conversationId:'c1',messageId:'optimistic:one'}});await a.event('error');assert.equal(document.querySelector('img'),null);assert.ok(document.querySelector('[aria-label="Retry Fixture photo"]'));});
test('lightbox uses intrinsic contained image, eager loading and full-size selected recovery',async t=>{const a=await mount(t,{layout:'preview',onOpen:undefined,reference:{conversationId:'c1',messageId:'stored:photo:2'}});const img=document.querySelector('img');assert.equal(img.style.position,'relative');assert.equal(img.style.objectFit,'contain');assert.equal(img.style.width,'auto');assert.equal(img.getAttribute('loading'),'eager');assert.equal(document.querySelector('[data-photo-state]').style.minWidth,'240px');await a.event('load');assert.equal(document.querySelector('[role="status"]'),null);await a.event('error');const recovery=new URL(document.querySelector('img').getAttribute('src'),'http://local');assert.equal(recovery.searchParams.get('photoIndex'),'2');assert.notEqual(recovery.searchParams.get('thumbnail'),'1');await a.event('error');assert.ok(document.querySelector('[aria-label="Retry Fixture photo"]'));await act(async()=>document.querySelector('button').click());assert.equal(document.querySelector('img').style.position,'relative');});
test('actual lightbox explicitly selects preview layout',()=>{const source=fs.readFileSync('components/inbox/message-panel.tsx','utf8');assert.match(source,/<InboxPhotoImage layout="preview" reference=\{imagePreview\.reference\}/);});
