const test=require('node:test'),assert=require('node:assert/strict');
const {loader,database}=require('./tenh-seven/harness.cjs');
const {createQuickPickerCache}=loader()('lib/inbox/quick-picker-cache.ts');
test('same-workspace overlapping picker loads share one read; empty data is cached',async()=>{const cache=createQuickPickerCache();let count=0,resolve;const read=()=>{count++;return new Promise(r=>resolve=r)};const a=cache.load('b1',read),b=cache.load('b1',read);await Promise.resolve();resolve({items:[],loadedAt:Date.now()});assert.equal(a,b);await a;assert.equal(count,1);assert.deepEqual(cache.get('b1').items,[]);assert.equal(cache.fresh('b1'),true);assert.equal(cache.get('b2'),undefined);});
test('failure retries and expired data remains available for background refresh',async()=>{const cache=createQuickPickerCache(1);await cache.load('b1',async()=>({items:['old'],loadedAt:0}));assert.equal(cache.fresh('b1'),false);await assert.rejects(cache.load('b1',async()=>{throw Error('Unavailable')}));assert.deepEqual(cache.get('b1').items,['old']);await cache.load('b1',async()=>({items:['new'],loadedAt:Date.now()}));assert.deepEqual(cache.get('b1').items,['new']);});
test('invalidation rejects late cache population without touching another workspace',async()=>{const cache=createQuickPickerCache();let resolve;const old=cache.load('b1',()=>new Promise(r=>resolve=r));await Promise.resolve();cache.invalidate('b1');await cache.load('b2',async()=>({items:['b2'],loadedAt:Date.now()}));resolve({items:['old-b1'],loadedAt:Date.now()});await old;assert.equal(cache.get('b1'),undefined);assert.deepEqual(cache.get('b2').items,['b2']);});
test('picker tab cache retains at most eight workspace catalogs',async()=>{const cache=createQuickPickerCache();for(let i=0;i<9;i++)await cache.load(String(i),async()=>({loadedAt:Date.now()}));assert.equal(cache.get('0'),undefined);assert.ok(cache.get('8'));});
function categories(allow){const db=database({saved_reply_categories:[{id:'one',business_id:'b1',name:'One'},{id:'two',business_id:'b2',name:'Two'}]});let checked=[];const load=loader({'@/lib/supabase/admin':{supabaseAdmin:db},'@/lib/auth/get-current-member':{getCurrentMember:async()=>({success:true,member:{business_id:'b1'}})},'@/lib/auth/require-permission':{},'@/lib/inbox/get-inbox-resource-access':{authorizeInboxBusinessAccess:async businessId=>{checked.push(businessId);return allow?{success:true}:{success:false,status:403,error:'Forbidden'}}}});return {db,checked,get:load('app/api/saved-reply-categories/route.ts').GET};}
test('category read defaults to current workspace and scopes an authorized requested workspace',async()=>{const app=categories(true);assert.equal((await(await app.get()).json()).categories[0].business_id,'b1');const response=await app.get({nextUrl:new URL('http://local/api/saved-reply-categories?businessId=b2')});const rows=(await response.json()).categories;assert.equal(rows.length,1);assert.equal(rows[0].business_id,'b2');assert.deepEqual(app.checked,['b2']);});
test('unauthorized category workspace is rejected before database reads',async()=>{const app=categories(false);assert.equal((await app.get({nextUrl:new URL('http://local/api/saved-reply-categories?businessId=b2')})).status,403);assert.equal(app.db.history.length,0);});
