const test=require('node:test'),assert=require('node:assert/strict'),{loader}=require('./tenh-seven/harness.cjs');const {trustedStoredBotEvent,runBoundedBotExecution}=loader()('lib/bot/execution-safety.ts');
const now='2026-10-01T12:00:00Z';const event=()=>({message:{id:'m',business_id:'b',conversation_id:'c',direction:'incoming',platform_message_id:'mid',platform_created_at:now,message_type:'text',message_text:'hello',sender_platform_id:'123'},conversation:{id:'c',business_id:'b',social_account_id:'ch',contact_id:'ct',source_type:'messenger'},contact:{id:'ct',business_id:'b',platform_user_id:'123'},channel:{id:'ch',business_id:'b',platform:'facebook',platform_account_id:'456',is_active:true}});
test('trusted event rejects cross-tenant identity, channel changes, forged sender, future timestamps and comment-as-DM',()=>{assert.equal(trustedStoredBotEvent(event(),now).kind,'customer');for(const change of [e=>e.contact.business_id='other',e=>e.conversation.social_account_id='other',e=>e.message.sender_platform_id='other',e=>e.channel.is_active=false,e=>e.message.platform_created_at='2027-01-01T00:00:00Z',e=>e.conversation.source_type='comment']){const e=event();change(e);assert.throws(()=>trustedStoredBotEvent(e,now));}});
const job=(patch={})=>({id:'j',businessId:'b',channelId:'ch',conversationId:'c',recipientId:'123',kind:'reply',dueAt:now,expiresAt:'2026-10-01T13:00:00Z',claimToken:'claim',generation:1,text:'Hello',...patch});
function harness(jobs=[job()]){const calls=[];return {calls,deps:{enabled:true,claim:async limit=>{calls.push(['claim',limit]);return jobs},reserve:async()=>({allowed:true,reason:'reserved',standardWindowOpen:true}),supported:()=>true,execute:async()=>{calls.push(['execute']);return {confirmed:true,providerId:'mid'}},finish:async(_j,status)=>calls.push(['finish',status])}};}
test('disabled worker makes no claim, query or effect',async()=>{const h=harness();h.deps.enabled=false;await runBoundedBotExecution(h.deps,now);assert.equal(h.calls.length,0)});
test('bounded worker clamps claims and records confirmed effect once',async()=>{const h=harness();await runBoundedBotExecution(h.deps,now,1000);assert.equal(h.calls[0][1],10);assert.equal(h.calls.filter(c=>c[0]==='execute').length,1);assert.equal(h.calls.at(-1)[1],'sent')});
test('held, expired, future or unsupported jobs never execute',async()=>{for(const patch of [{expiresAt:now},{dueAt:'2026-10-02T00:00:00Z'},{dueAt:'invalid'},{}]){const h=harness([job(patch)]);h.deps.reserve=async()=>({allowed:false,reason:'held',standardWindowOpen:true});await runBoundedBotExecution(h.deps,now);assert.equal(h.calls.filter(c=>c[0]==='execute').length,0)}const h=harness();h.deps.supported=()=>false;await runBoundedBotExecution(h.deps,now);assert.equal(h.calls.at(-1)[1],'unsupported')});
test('reply eligibility never substitutes HUMAN_AGENT for standard window',async()=>{const h=harness();h.deps.reserve=async()=>({allowed:true,reason:'human agent only',standardWindowOpen:false});await runBoundedBotExecution(h.deps,now);assert.equal(h.calls.at(-1)[1],'cancelled');assert.equal(h.calls.filter(c=>c[0]==='execute').length,0)});
test('unknown effect and transport timeout require review, never automatic retry',async()=>{for(const execute of [async()=>({confirmed:false}),async()=>{throw Error('timeout')}]){const h=harness();let sends=0;h.deps.execute=async()=>{sends++;return execute()};await runBoundedBotExecution(h.deps,now);assert.equal(sends,1);assert.equal(h.calls.at(-1)[1],'needs_review')}});
test('result persistence failure escapes without retrying an already executed provider effect',async()=>{const h=harness();h.deps.finish=async()=>{throw Error('ledger unavailable')};await assert.rejects(runBoundedBotExecution(h.deps,now),/ledger unavailable/);assert.equal(h.calls.filter(c=>c[0]==='execute').length,1)});
test('duplicate claims fail before any effects',async()=>{const h=harness([job(),job()]);await assert.rejects(runBoundedBotExecution(h.deps,now),/duplicate_claim/);assert.equal(h.calls.filter(c=>c[0]==='execute').length,0)});
