const test=require('node:test'),assert=require('node:assert/strict'),React=require('react'),{act}=React,{createRoot}=require('react-dom/client'),{JSDOM}=require('jsdom'),{loader}=require('./tenh-seven/harness.cjs');
test('thirteen Bot choices preserve scoped unfinished fields and valid deep links without remounting the editor',async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://fixture.test/dashboard/tenh-bot?bot=keyword_faq'});global.window=dom.window;global.document=dom.window.document;global.IS_REACT_ACT_ENVIRONMENT=true;
 const load=loader({react:React,'react/jsx-runtime':require('react/jsx-runtime'),'@/components/settings/auto-reply-settings':{AutoReplySettings:()=>React.createElement('p',null,'Legacy comments')},'@/components/settings/bot-draft-settings':{BotDraftSettings:({selectedKind})=>{const [value,setValue]=load('lib/bot/use-editor-field.ts').useBotEditorField(selectedKind,'');return React.createElement('button',{id:'editor',onClick:()=>setValue('unfinished '+selectedKind)},value||selectedKind)}},'@/lib/display/foreground-loading':{useForegroundLoading:()=>{}}},{window:dom.window,document:dom.window.document});
 const {TenhBotWorkspace}=load('components/bot/tenh-bot-workspace.tsx'),root=createRoot(document.getElementById('root'));
 try{await act(async()=>root.render(React.createElement(TenhBotWorkspace)));assert.equal(document.querySelectorAll('nav button').length,13);assert.equal(document.querySelector('[aria-current="page"]').textContent,'Keyword FAQ');assert.equal(document.getElementById('editor').textContent,'keyword_faq');
 await act(async()=>document.getElementById('editor').click());const choose=label=>[...document.querySelectorAll('nav button')].find(x=>x.textContent===label);
 await act(async()=>choose('Welcome / Away').click());assert.equal(document.getElementById('editor').textContent,'welcome_away');await act(async()=>document.getElementById('editor').click());await act(async()=>choose('Keyword FAQ').click());assert.equal(document.getElementById('editor').textContent,'unfinished keyword_faq');assert.equal(new URL(window.location.href).searchParams.get('bot'),'keyword_faq');
 await act(async()=>choose('Facebook Comment Auto Reply').click());assert.ok(document.getElementById('editor').parentElement.hidden);await act(async()=>choose('Welcome / Away').click());assert.equal(document.getElementById('editor').textContent,'unfinished welcome_away');
 window.history.replaceState(null,'','?bot=conditional_followups');await act(async()=>window.dispatchEvent(new window.PopStateEvent('popstate')));assert.equal(document.getElementById('editor').textContent,'conditional_followups');assert.ok([...document.querySelectorAll('nav button')].every(x=>x.type==='button'));
 }finally{await act(async()=>root.unmount());dom.window.close();}
});
