import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {resolve} from 'node:path';import {readFileSync} from 'node:fs';
const root=process.env.TENH_PGLITE_ROOT;
if(!root){test('execution ledger SQL',{skip:'Preinstalled disposable PGlite required.'},()=>{});}else{
const {PGlite}=createRequire(resolve(root,'package.json'))('@electric-sql/pglite');
test('durable ledger deduplicates trusted events, holds on staff, ignores echoes and atomically reserves bounded jobs',async()=>{const db=new PGlite(),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,b=id(1),ch=id(2),ct=id(3),c=id(4),m=id(5),staff=id(6),echo=id(7);try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create table businesses(id uuid primary key);create table social_accounts(id uuid primary key,business_id uuid,is_active boolean,platform text);create table contacts(id uuid primary key,business_id uuid,platform_user_id text);create table conversations(id uuid primary key,business_id uuid,social_account_id uuid,contact_id uuid,source_type text);create table messages(id uuid primary key,business_id uuid,conversation_id uuid,platform_message_id text,platform_created_at timestamptz,direction text,is_echo boolean,sender_platform_id text);insert into businesses values('${b}');insert into social_accounts values('${ch}','${b}',true,'facebook');insert into contacts values('${ct}','${b}','123');insert into conversations values('${c}','${b}','${ch}','${ct}',null);insert into messages values('${m}','${b}','${c}','mid',clock_timestamp(),'incoming',false,'123');`);
 await db.exec("alter table messages add column raw_payload jsonb default '{}'::jsonb;alter table messages add column message_text text;alter table social_accounts add column platform_account_id text default '456';alter table conversations add column assigned_to uuid;alter table conversations add column updated_at timestamptz default now();create table team_members(id uuid primary key,business_id uuid,is_active boolean);create table team_notifications(business_id uuid,recipient_member_id uuid,actor_member_id uuid,notification_type text,title text,body text,link text,conversation_id uuid);");
 await db.exec("create table business_subscriptions(business_id uuid,status text,current_period_end timestamptz,trial_ends_at timestamptz,created_at timestamptz);alter table team_members add column user_id uuid;alter table team_members add column created_at timestamptz;alter table social_accounts add column facebook_token_status text;alter table social_accounts add column telegram_token_status text;alter table contacts add column full_name text;alter table contacts add column phone text;alter table conversations add column status text default 'open';alter table conversations add column unread_count integer default 0;alter table conversations add column is_pinned boolean default false;alter table conversations add column last_message_at timestamptz;alter table conversations add column last_message_text text;create table contact_tags(contact_id uuid,tag_id uuid);create table tags(id uuid,business_id uuid,name text);");
 await db.exec(readFileSync(new URL('../docs/sql/tenh-release-install-disabled.sql',import.meta.url),'utf8'));
 const verification=(await db.query(readFileSync(new URL('../docs/sql/tenh-release-postinstall-summary.sql',import.meta.url),'utf8'))).rows[0].tenh_release_postinstall;
 assert.equal(verification.tables.length,5);assert.ok(verification.tables.every(t=>t.present&&t.rls&&t.no_public_grants&&t.no_client_policies));
 assert.equal(verification.functions.length,11);assert.ok(verification.functions.every(f=>f.present&&f.security_invoker&&f.no_public_grants&&!f.effective_execute.anon&&!f.effective_execute.authenticated&&f.effective_execute.service_role));
 assert.equal(verification.disabled_state.enabled_rule_sets,0);assert.equal(verification.disabled_state.unpaused_controls,0);assert.equal(verification.paging_rpc_present,true);
 const record=async(mid)=> (await db.query('select tenh_bot_record_event($1,1,\'[]\') result',[mid])).rows[0].result;
 assert.equal((await record(m)).paused,true);assert.equal((await record(m)).duplicate,true);
 await db.exec(`insert into messages values('${staff}','${b}','${c}','staff',clock_timestamp(),'outgoing',false,'page');`);assert.equal((await record(staff)).held,true);
 const before=(await db.query('select generation,human_hold from tenh_bot_recipient_state')).rows[0];assert.equal(before.human_hold,true);
 await db.exec(`insert into messages values('${echo}','${b}','${c}','echo',clock_timestamp(),'outgoing',true,'page');`);assert.equal((await record(echo)).echo,true);assert.deepEqual((await db.query('select generation,human_hold from tenh_bot_recipient_state')).rows[0],before);
 // Test-only activation is confined to this disposable database.
 await db.exec(`insert into tenh_bot_rule_sets(business_id,social_account_id,rules) values('${b}','${ch}','[{"id":"r1","cooldownMinutes":0}]');alter table tenh_bot_rule_sets drop constraint tenh_bot_rule_sets_enabled_check;update tenh_bot_rule_sets set enabled=true,activated_at=clock_timestamp()-interval '1 minute';insert into tenh_bot_execution_controls values('${b}',false);insert into tenh_bot_execution_jobs(business_id,social_account_id,conversation_id,recipient_id,message_id,rule_id,rule_revision,generation,action_key,action,due_at,expires_at) select '${b}','${ch}','${c}','123','${m}','r1',1,generation,'unique','{"kind":"reply"}',clock_timestamp(),clock_timestamp()+interval '1 hour' from tenh_bot_recipient_state;`);
 assert.equal((await db.query('select * from tenh_bot_claim_jobs(1000)')).rows.length,0);
 await db.exec('update tenh_bot_recipient_state set human_hold=false');const job=(await db.query('select * from tenh_bot_claim_jobs(1000)')).rows[0];assert.ok(job.claim_token);assert.equal((await db.query('select * from tenh_bot_claim_jobs(1000)')).rows.length,0);
 const reservation=(await db.query('select tenh_bot_reserve_job($1,$2) result',[job.id,job.claim_token])).rows[0].result;assert.equal(reservation.allowed,true);assert.equal(reservation.standardWindowOpen,true);
 assert.equal((await db.query("select tenh_bot_finish_job($1,$2,'needs_review','uncertain',null) result",[job.id,job.claim_token])).rows[0].result,true);assert.equal((await db.query('select * from tenh_bot_claim_jobs(10)')).rows.length,0);
}finally{await db.close();}});
}
