const {test}=require('node:test'), assert=require('node:assert/strict');
const {loader,database,baseSeed,ROOT}=require('./harness.cjs');
const fs=require('fs'),path=require('path');
const load=loader(); const {facebookNativeReply,facebookReplyTarget}=load('lib/facebook/native-reply.ts');
const {getMessageActions,getDeletedMessageText,isMessageDeleted}=load('lib/inbox/message-actions.ts');
function msg(patch={}){return {id:'local1',conversation_id:'conv1',business_id:'b1',platform_message_id:'mid1',message_type:'text',message_text:'Original',attachment_url:null,direction:'incoming',raw_payload:{},...patch}}
const response=msg({id:'reply1',platform_message_id:'mid2',raw_payload:{message:{reply_to:{mid:'mid1'}}}});
test('Incoming Facebook native reply maps parent in this conversation',()=>{const p=facebookNativeReply(response,[msg()]);assert.equal(p.text,'Original');assert.equal(p.localMessageId,'local1')});
test('Reply matching cannot cross customer conversation',()=>{const p=facebookNativeReply(response,[msg({conversation_id:'different'})]);assert.equal(p.localMessageId,null);assert.match(p.text,/not available/)});
test('Plain Facebook message is not labelled a native reply',()=>assert.equal(facebookNativeReply(msg(),[msg()]),null));
test('TENH-only outgoing reference is not reported as native',()=>assert.equal(facebookNativeReply(msg({raw_payload:{tenh_reply:{scope:'tenh',preview_text:'cached'}}}),[]),null));
test('Facebook self-reference is ignored',()=>assert.equal(facebookNativeReply(msg({raw_payload:{message:{reply_to:{mid:'mid1'}}}}),[]),null));
test('Telegram native reply is not reinterpreted as Facebook reply',()=>assert.equal(facebookNativeReply({...response,platform_message_id:'telegram:123:1'},[msg()]),null));
test('Malformed native ID ignored',()=>{for(const mid of [123,{},null,'','x'.repeat(501)])assert.equal(facebookReplyTarget({message:{reply_to:{mid}}}),null)});
test('Native quote follows edited parent text',()=>assert.equal(facebookNativeReply(response,[msg({message_text:'Edited'})]).text,'Edited'));
test('Deleted parent does not leak original quote text',()=>{const p=facebookNativeReply(response,[msg({raw_payload:{tenh_deleted:{source:'tenh',deleted_by_name:'Dara'}}})]);assert.notEqual(p.text,'Original');assert.match(p.text,/deleted/i)});
test('Validated saved reply allowed only for same conversation and mid',()=>{const r={...response,raw_payload:{...response.raw_payload,tenh_facebook_reply:{platformMessageId:'mid1',conversationId:'conv1',text:'Saved'}}};assert.equal(facebookNativeReply(r,[]).text,'Saved');r.raw_payload.tenh_facebook_reply.conversationId='other';assert.notEqual(facebookNativeReply(r,[]).text,'Saved')});
test('Reply enrichment database error never blocks incoming delivery',async()=>{const l=loader({'@/lib/supabase/admin':{supabaseAdmin:{from(){throw new Error('offline')}}}});assert.equal(await l('lib/facebook/capture-native-reply.ts').captureFacebookNativeReply(response.raw_payload,{businessId:'b1',conversationId:'conv1',messageId:'mid2'}),null)});
function telegram(raw={}){const seed=baseSeed();seed.social_accounts[0].platform='telegram';seed.messages=[msg({platform_message_id:'telegram:123:10',platform_created_at:'2026-09-12T00:00:00Z',raw_payload:raw})];const db=database(seed);const l=loader({'@/lib/supabase/admin':{supabaseAdmin:db}});return {db,run:connectionId=>l('lib/telegram/process-edited-message.ts').processTelegramEditedText({businessId:'b1',connectionId,update:{update_id:1,edited_message:{message_id:10,chat:{id:123,type:'private'},from:{id:123,is_bot:false},text:'Edited',edit_date:1789171500}}})}}
test('Telegram edit preserves existing pin metadata',async()=>{const h=telegram({tenh_pin:{pinned:true,at:'now'}});assert.equal((await h.run('s1')).edited,true);assert.equal(h.db.tables.messages[0].message_text,'Edited');assert.equal(h.db.tables.messages[0].raw_payload.tenh_pin.pinned,true)});
test('Late Telegram edit cannot resurrect TENH deletion',async()=>{const h=telegram({tenh_deleted:{source:'tenh',deleted_by_name:'Dara'}});const r=await h.run('s1');assert.equal(r.ignored,true);assert.equal(r.reason,'message_deleted');assert.equal(h.db.tables.messages[0].message_text,'Original');assert.equal(h.db.history.filter(x=>x.op==='update').length,0)});
test('Telegram edits are scoped to this exact bot connection',async()=>{const h=telegram();const r=await h.run('another-bot');assert.equal(r.ignored,true);assert.equal(h.db.history.filter(x=>x.op==='update').length,0)});
test('Older Telegram edit does not overwrite newer edit',async()=>{const h=telegram({tenh_edit:{edited_at:'2030-01-01T00:00:00Z'}});assert.equal((await h.run('s1')).reason,'older_edit');assert.equal(h.db.tables.messages[0].message_text,'Original')});
for(const platform of ['facebook','telegram'])for(const direction of ['outgoing','incoming'])for(const kind of ['text','image','video','file'])test(`${platform} ${direction} ${kind}: actions preserved`,()=>{
 const m=msg({direction,message_type:kind,platform_message_id:platform==='telegram'?'telegram:123:10':'mid1'});const a=Object.entries(getMessageActions(m,platform)).filter(([,yes])=>yes).map(([key])=>key);
 const expected=platform==='facebook'?['reply','pin']:kind!=='text'?['reply','delete']:direction==='outgoing'?['reply','pin','edit','delete']:['reply','delete'];assert.deepEqual(a,expected);
});
test('Deleted messages have no new action controls',()=>{assert.equal(Object.values(getMessageActions(msg({raw_payload:{tenh_deleted:{}}}),'facebook')).some(Boolean),false)});
test('All six stickers are valid shipped PNGs',()=>{for(const name of ['hello','thanks','ok','love','sorry','delivery']){const file=fs.readFileSync(path.join(ROOT,'public/stickers/tenh',name+'.png'));assert.equal(file.subarray(0,8).toString('hex'),'89504e470d0a1a0a');assert.equal(file.readUInt32BE(16),256);assert.equal(file.readUInt32BE(20),256)}});
test('Web avatar delegates unknown links to extension and retains direct saved links',()=>{const s=fs.readFileSync(path.join(ROOT,'components/inbox/customer-facebook-avatar.tsx'),'utf8');assert.match(s,/openFacebookProfile/);assert.doesNotMatch(s,/business\.facebook\.com/);assert.match(s,/target="_blank"/)});
test('Absent-extension Business Suite button uses explanatory notice, not window.open',()=>{const s=fs.readFileSync(path.join(ROOT,'components/inbox/companion-facebook-action.tsx'),'utf8');assert.match(s,/if \(!installed\)/);assert.doesNotMatch(s,/window\.open|business\.facebook\.com/)});
test('Block storage is RLS-protected and server-write only',()=>{const s=fs.readFileSync(path.join(ROOT,'supabase/migrations/202609120001_tenh_seven_updates.sql'),'utf8');assert.match(s,/ENABLE ROW LEVEL SECURITY/);assert.match(s,/REVOKE ALL.*anon, authenticated/);assert.match(s,/GRANT SELECT.*authenticated/);assert.match(s,/tm.user_id = auth.uid\(\)/)});
