const {test}=require('node:test'),assert=require('node:assert/strict');const {setup,baseSeed}=require('./harness.cjs');
const BLOCK='app/api/conversations/[conversationId]/facebook-block/route.ts', PROFILE='app/api/conversations/[conversationId]/facebook-profile/route.ts',OPEN='app/api/extension/conversations/open-context/route.ts',GROUP='app/api/team-chat/rooms/[roomId]/route.ts';
async function json(response){return {status:response.status,data:await response.json()};}
test('Block requires and records positive Meta confirmation',async()=>{const h=setup();const r=await json(await h.load(BLOCK).POST(h.request({blocked:true}),h.context));assert.equal(r.status,200);assert.equal(h.db.tables.facebook_customer_blocks[0].is_blocked,true);assert.equal(h.db.tables.facebook_customer_blocks[0].updated_by_name,'Agent One');assert.equal(h.db.tables.facebook_customer_blocks[0].operation_id,null);assert.deepEqual(JSON.parse(h.calls[0].init.body),{user_ids:[{id:'100076611888104'}],actions:['block_user']});assert.equal(h.db.tables.conversation_activity.length,1)});
test('Unblock uses upstream unblock_user',async()=>{const h=setup();await h.load(BLOCK).POST(h.request({blocked:true}),h.context);await h.load(BLOCK).POST(h.request({blocked:false}),h.context);assert.equal(h.db.tables.facebook_customer_blocks[0].is_blocked,false);assert.equal(JSON.parse(h.calls[1].init.body).actions[0],'unblock_user')});
test('Provider permission refusal does not mark blocked',async()=>{const h=setup({fetchResults:[{error:{code:10}}]});const r=await json(await h.load(BLOCK).POST(h.request({blocked:true}),h.context));assert.equal(r.status,502);assert.equal(h.db.tables.facebook_customer_blocks[0].is_blocked,false);assert.equal(h.db.tables.facebook_customer_blocks[0].operation_id,null)});
test('Network failure releases lock without claiming success',async()=>{const h=setup({fetchThrow:true});const r=await json(await h.load(BLOCK).POST(h.request({blocked:true}),h.context));assert.equal(r.status,502);assert.equal(h.db.tables.facebook_customer_blocks[0].is_blocked,false);assert.equal(h.db.tables.facebook_customer_blocks[0].operation_id,null)});
for(const denied of ['denied','permissionDenied'])test(`Block ${denied} avoids all provider calls`,async()=>{const h=setup({[denied]:true});const r=await h.load(BLOCK).POST(h.request({blocked:true}),h.context);assert.equal(r.status,403);assert.equal(h.calls.length,0)});
for(const body of [null,{}, {blocked:'true'},{blocked:1}])test(`Block malformed ${JSON.stringify(body)}`,async()=>{const h=setup();assert.equal((await h.load(BLOCK).POST(h.request(body),h.context)).status,400);assert.equal(h.calls.length,0)});
test('CSRF origin rejection',async()=>{const h=setup();assert.equal((await h.load(BLOCK).POST(h.request({blocked:true},'POST','https://evil.test'),h.context)).status,403);assert.equal(h.calls.length,0)});
test('Missing migration prevents upstream block',async()=>{const seed=baseSeed();delete seed.facebook_customer_blocks;const h=setup({seed});assert.equal((await h.load(BLOCK).POST(h.request({blocked:true}),h.context)).status,503);assert.equal(h.calls.length,0)});
test('Fresh two-agent lease prevents conflicting operation',async()=>{const seed=baseSeed();seed.facebook_customer_blocks.push({business_id:'b1',social_account_id:'s1',contact_id:'c1',is_blocked:false,operation_id:'other',operation_started_at:new Date().toISOString()});const h=setup({seed});assert.equal((await h.load(BLOCK).POST(h.request({blocked:true}),h.context)).status,409);assert.equal(h.calls.length,0)});
test('Expired lease can be claimed safely',async()=>{const seed=baseSeed();seed.facebook_customer_blocks.push({business_id:'b1',social_account_id:'s1',contact_id:'c1',is_blocked:false,operation_id:'old',operation_started_at:'2020-01-01T00:00:00Z'});const h=setup({seed});assert.equal((await h.load(BLOCK).POST(h.request({blocked:true}),h.context)).status,200)});
test('Expired Meta token retries once via existing token refresh',async()=>{const h=setup({fetchResults:[{error:{code:190}},{success:true}]});assert.equal((await h.load(BLOCK).POST(h.request({blocked:true}),h.context)).status,200);assert.equal(h.refreshes(),1);assert.equal(h.calls.length,2)});
test('Confirmed provider / failed persistence is explicit partial failure',async()=>{const h=setup();h.db.failures.push({table:'facebook_customer_blocks',op:'update',when:q=>q.body.is_blocked===true});const r=await json(await h.load(BLOCK).POST(h.request({blocked:true}),h.context));assert.equal(r.status,503);assert.equal(r.data.providerConfirmed,true)});
test('Other Page block remains untouched',async()=>{const seed=baseSeed();seed.facebook_customer_blocks.push({business_id:'b1',social_account_id:'other',contact_id:'c1',is_blocked:true});const h=setup({seed});await h.load(BLOCK).POST(h.request({blocked:false}),h.context);assert.equal(h.db.tables.facebook_customer_blocks.find(x=>x.social_account_id==='other').is_blocked,true)});
test('Profile saves confirmed public ID without altering Messenger ID',async()=>{const h=setup();const r=await json(await h.load(PROFILE).PATCH(h.request({profileUrl:'61555135812581',confirmed:true},'PATCH'),h.context));assert.equal(r.status,200);assert.equal(r.data.profileUrl,'https://www.facebook.com/profile.php?id=61555135812581');assert.equal(h.db.tables.contacts[0].platform_user_id,'100076611888104');assert.equal(h.db.tables.contacts[0].facebook_profile_id,'61555135812581')});
for(const link of ['100076611888104','393342417206745','javascript:alert(1)','https://facebook.com.evil.test/name','https://business.facebook.com/latest/inbox/','https://www.facebook.com/profile.php?id=123&id=456'])test(`Profile rejects ${link}`,async()=>{const h=setup();assert.equal((await h.load(PROFILE).PATCH(h.request({profileUrl:link,confirmed:true},'PATCH'),h.context)).status,400)});
test('Public username remains username, no invented ID',async()=>{const h=setup();const r=await json(await h.load(PROFILE).PATCH(h.request({profileUrl:'https://www.facebook.com/example.customer',confirmed:true},'PATCH'),h.context));assert.equal(r.status,200);assert.equal(h.db.tables.contacts[0].facebook_profile_id,null);assert.equal(h.db.tables.contacts[0].facebook_profile_url,'https://www.facebook.com/example.customer')});
test('Profile requires confirmation',async()=>{const h=setup();assert.equal((await h.load(PROFILE).PATCH(h.request({profileUrl:'61555135812581'},'PATCH'),h.context)).status,400)});
test('Profile prevents stale user edit',async()=>{const h=setup();assert.equal((await h.load(PROFILE).PATCH(h.request({profileUrl:'61555135812581',confirmed:true,expectedUpdatedAt:'OLD'},'PATCH'),h.context)).status,409)});
test('Profile removal preserves customer name',async()=>{const h=setup();assert.equal((await h.load(PROFILE).PATCH(h.request({profileUrl:null},'PATCH'),h.context)).status,200);assert.equal(h.db.tables.contacts[0].full_name,'Customer')});
const openBody={pageId:'393342417206745',threadId:'100076611888104',conversationId:'conv1',businessId:'b1'};
test('Conversation open authorizes exact tenant/Page/customer',async()=>{const h=setup();const r=await json(await h.load(OPEN).POST(h.request(openBody)));assert.equal(r.status,200);assert.equal(r.data.verified,true);assert.equal(r.data.threadId,openBody.threadId)});
for(const patch of [{pageId:'111'},{threadId:'222'},{businessId:'b2'},{conversationId:'other'},{threadId:'uuid-conversation'}])test(`Conversation open rejects mismatch ${JSON.stringify(patch)}`,async()=>{const h=setup();assert.equal((await h.load(OPEN).POST(h.request({...openBody,...patch}))).status,403)});
test('Revoked device cannot navigate',async()=>{const h=setup({denied:true});assert.equal((await h.load(OPEN).POST(h.request(openBody))).status,403)});
function groupSetup(general=false,role='owner'){const seed=baseSeed();seed.team_chat_rooms.push({id:'r1',business_id:'b1',is_general:general,name:'Support',description:'Old',slug:'support-heart'});return setup({seed,role})}
test('Edit group name and description leaves icon intact',async()=>{const h=groupSetup();const r=await json(await h.load(GROUP).PATCH(h.request({name:'Sales',description:'Sales team'},'PATCH'),h.context));assert.equal(r.status,200);assert.equal(r.data.room.name,'Sales');assert.equal(r.data.room.icon,'heart');assert.equal(h.db.tables.team_chat_rooms[0].description,'Sales team')});
test('General name and description are protected server-side',async()=>{const h=groupSetup(true);assert.equal((await h.load(GROUP).PATCH(h.request({name:'Wrong',description:'Wrong'},'PATCH'),h.context)).status,400);assert.equal(h.db.tables.team_chat_rooms[0].name,'Support')});
test('Agent cannot edit group as admin',async()=>{const h=groupSetup(false,'agent');assert.equal((await h.load(GROUP).PATCH(h.request({name:'Wrong'},'PATCH'),h.context)).status,403)});
for(const body of [null,[],{name:''},{name:'x'.repeat(81)},{description:42}])test(`Invalid group edit ${JSON.stringify(body)}`,async()=>{const h=groupSetup();assert.equal((await h.load(GROUP).PATCH(h.request(body,'PATCH'),h.context)).status,400)});

test('Profile edit honors customer manage permission',async()=>{const h=setup({permissionDenied:true});assert.equal((await h.load(PROFILE).PATCH(h.request({profileUrl:'61555135812581',confirmed:true},'PATCH'),h.context)).status,403);assert.equal(h.db.tables.contacts[0].facebook_profile_id,null)});
