const messages: Record<string, string> = {
  profile_conversation_link_unavailable: "TENH could not verify this customer's conversation link. The automatic lookup could not continue.",
  profile_conversation_not_found: "Meta returned no conversation for this Page and Messenger customer ID.",
  profile_conversation_participants_unmatched: "TENH could not match Meta's conversation participants to this Page and customer.",
  profile_conversation_link_unsupported: "Meta returned a conversation link, but TENH does not support its format yet. This needs a TENH update.",
  profile_conversation_link_missing: "Meta returned the matching conversation without a link. TENH could not continue automatic lookup.",
  profile_conversation_name_unavailable: "Meta returned the conversation link without a customer name needed to verify the loaded profile.",
  profile_conversation_request_failed: "Meta rejected TENH's conversation request. The API response needs checking before retrying.",
  profile_conversation_ambiguous: "Meta returned more than one matching conversation. TENH could not choose a customer profile safely.",
  profile_conversation_access_unavailable: "Meta refused access to this customer's conversation link. Check this Page's connection in Integrations.",
  profile_conversation_lookup_failed: "TENH could not retrieve this customer's conversation link from Meta. Please retry shortly.",
  facebook_no_contact_card: "Business Suite shows no contact card for the loaded conversation, so its public profile link could not be read.",
  facebook_inbox_load_failed: "Business Suite could not load this customer's conversation. TENH has not obtained a public profile link.",
  conversation_selection_unverified: "Facebook did not expose the selected customer clearly enough to verify this profile. TENH did not guess a match.",
  profile_messenger_required: "Automatic profile lookup is available from the customer's Messenger conversation. Open that conversation and retry.",
  profile_navigation_moved_to_website: "Update TENH Companion to version 1.2.26 or later, then refresh TENH and Facebook.",
  facebook_session_needed: "Sign in to Facebook in this Chrome profile, then retry.",
  profile_link_not_available: "A verified Facebook profile link is not available for this customer yet. No tab was opened.",
  facebook_tab_in_use: "Return to TENH with the Facebook Page inbox in a background tab, then retry.",
  profile_lookup_busy: "Another customer profile lookup is in progress. Please retry shortly.",
  profile_link_missing: "Facebook did not return a matching customer profile. The automatic lookup could not complete.",
  profile_customer_heading_missing: "TENH could not identify this customer's name in the loaded Facebook customer card.",
  profile_link_not_rendered: "Facebook's loaded customer card did not expose a public profile link after lookup.",
  profile_link_label_unrecognized: "TENH found links in the customer card but could not identify the profile link. Its label needs checking.",
  profile_link_format_unsupported: "The customer card showed a link that TENH could not verify as a public Facebook profile.",
  profile_action_without_link: "TENH found View profile but could not read a destination URL from that control. Copy the lookup details to check this layout.",
  ambiguous_customer: "More than one matching customer was found. TENH did not choose a profile.",
  ambiguous_profile: "Facebook showed more than one matching profile link. TENH did not choose one.",
  page_mismatch_or_sign_in: "The lookup could not load this conversation's Facebook Page. Check that your Facebook account can access that Page.",
  customer_not_found: "The customer search did not return one stable matching result. The name may differ on Facebook or the search may still be loading.",
  search_unavailable: "TENH could not find the search field in Business Suite. This needs a search-detection fix, not a new customer ID.",
  search_interrupted: "Business Suite changed or reset the search field during lookup. Please retry.",
  profile_link_unavailable: "Facebook has not exposed a verified profile link for this customer. No tab was opened.",
  extension_refresh_required: "The extension scripts need reloading. Reload TENH Companion, then refresh TENH and Facebook.",
  extension_request_failed: "The browser could not complete the extension request. Reload TENH Companion and refresh TENH.",
  extension_timeout: "TENH did not receive an extension reply before the timeout. Check that TENH Companion is enabled and refresh TENH.",
  facebook_bridge_unavailable: "TENH Companion could not read the matching customer profile from the loaded Facebook tab.",
  profile_resolution_unavailable: "The extension's Facebook lookup was interrupted or failed to run. Copy the error details so this can be diagnosed.",
  profile_context_incomplete: "This conversation is missing its workspace, Facebook Page, Messenger customer ID or customer name.",
  profile_page_mismatch: "The extension returned a profile for a different Page. TENH did not open it.",
  profile_url_unsupported: "The extension returned a link that TENH cannot verify as a Facebook profile. TENH did not open it.",
  facebook_sign_in_required: "Sign in to Facebook in this Chrome profile, complete any security check, then retry.",
  facebook_load_timeout: "Facebook took too long to load. Check your connection and retry.",
  conversation_mismatch: "Facebook did not select this exact customer conversation. TENH will not open a profile based only on a name match.",
  profile_context_unmatched: "TENH could not authorize this Page and Messenger conversation for your connected browser. Check the selected workspace and extension connection.",
  profile_context_mismatch: "The workspace, Page or conversation changed or did not match. TENH did not open a different customer's profile.",
  tenh_sign_in_required: "This browser's TENH connection needs to be restored. Sign in to TENH and retry.",
  tenh_authorization_unavailable: "TENH could not check access to this conversation. Check your connection and retry.",
  profile_lookup_timeout: "Facebook did not expose a profile link before the lookup timed out. Please retry.",
  profile_lookup_interrupted: "The Facebook lookup tab changed during the request. Please retry.",
  profile_identity_unverified: "Facebook did not show a loaded profile matching this customer. No guessed profile was opened.",
  profile_validation_unavailable: "TENH could not confirm that the Facebook profile loaded. Please retry.",
  facebook_content_unavailable: "Facebook says this profile is unavailable to your current Facebook account. TENH cannot override that restriction.",
  profile_resolution_expired: "The profile-opening request expired or its customer context changed. Click the photo again.",
  profile_tab_unavailable: "Chrome could not open the profile tab. Use View Facebook profile below to open the resolved link.",
  profile_open_unconfirmed: "Chrome did not confirm the profile tab opened. Check your tabs before retrying.",
  not_profile_route: "Facebook redirected away from a customer profile. TENH did not open that destination.",
  not_facebook: "Facebook redirected to an unsupported destination. TENH did not open it.",

};

export function profileLookupError(reason: string): string {
  return messages[reason] ?? "The profile lookup failed. Copy the error details so the failing step can be checked.";
}
