const definitions:Record<string,string>={
  "team-performance":"Team Performance counts the first outgoing reply, including automation, after the first incoming message in the period. SLA includes replied conversations and overdue unanswered conversations. This differs from the overview's verified human-only population. Resolution is inferred from current status timestamps, not recorded resolution activity; it remains unverified as a historical event metric.",
  "agent-performance":"These are member-attributed response samples, including any attributed automation. They are not overall human performance. Per-agent conversation counts overlap when several agents reply in one thread; never sum them or average their medians. SLA includes attributed completed replies only and differs from Team Performance's denominator. Resolution actions are events, not unique resolved conversations.",
  "channel-performance":"This report selects conversations created in the period, then reads their entire message history. Message volumes are lifetime cohort volumes, not period activity. Outgoing-first threads can be misclassified because the first outgoing message is used rather than the first outgoing message after the customer asks. These timings and unanswered counts are flagged, not verified. Comment threads and messaging conversations are separate units; overall conversation counts exclude comments.",
  "team-workload":"Current snapshot, independent of date filters. Unread is a count of unread messages, not unread conversations. Member totals omit unassigned work. The overview counts unique unread Inbox threads and includes unassigned work. Overdue counts are unfinished follow-up reminders, not conversations. Channel population may include additional authorized channels beyond the overview's three shared channel types.",
  "customer-insights":"Identity is the saved contact ID; customers are not merged across channels. New counts contacts created in the period, including inactive contacts. Returning means an older contact with incoming activity. Active includes incoming, outgoing and system messages, so new + returning does not reconstruct active. Channel rows currently combine Telegram with Messenger; do not interpret that row as Facebook-only.",
  "conversation-reports":"Received includes unique conversations and comment threads with period incoming messages, including spam. Current states and waiting are restricted to that period's received cohort, not the whole current queue. Total messages includes system events. The channel RPC combines Telegram with Messenger, and busiest hours returns only six first-incoming-hour buckets. Those channel/hour labels are unverified as a complete channel/activity breakdown. Resolutions are first recorded resolved/closed events after cohort incoming activity, one per conversation.",
};
export function AnalyticsDefinitionNotice({view}:{view:string}) {
  const text=definitions[view];if(!text)return null;
  return <aside data-analytics-definition-notice className="mb-4 rounded-xl border border-amber-200 bg-amber-50/60 px-4 py-3 text-xs leading-6 text-amber-900"><strong>Metric scope &amp; verification: </strong>{text}<p>Drilldowns preserve workspace and exact date bounds. The original report populations above intentionally differ from the human overview; they must not be treated as equivalent totals.</p><p>Legacy RPC daily/hour grouping depends on the database session timezone; selected-timezone bucket accuracy remains unverified. Legacy zero-duration results without eligible responses are unavailable measurements.</p></aside>;
}
