const {test}=require('node:test'),assert=require('node:assert/strict');const {setup,CONV}=require('./harness.cjs');
const file='app/api/save-profile-url/route.ts',psid='100076611888104',pageId='393342417206745',publicProfileUrl='https://www.facebook.com/profile.php?id=61500000000001';
const payload={psid,pageId,publicProfileUrl};
async function post(e,body=payload,opts={bearer:true}){const r=await e.load(file).POST(e.request(body,opts));return {status:r.status,data:await r.json()};}
test('Authorized extension saves public URL to existing contact, not a new database',async()=>{const e=setup(),r=await post(e);assert.equal(r.status,200);assert.equal(r.data.pageId,pageId);assert.equal(r.data.conversationId,CONV);assert.equal(e.db.tables.contacts[0].facebook_profile_id,'61500000000001');assert.equal(e.db.tables.contacts[0].platform_user_id,psid);assert.equal(e.events[0].metadata.identityVerifiedByMeta,false);assert.equal(e.calls.length,0)});
test('Same observation is idempotent and produces no extra audit write',async()=>{const e=setup();await post(e);const r=await post(e);assert.equal(r.data.unchanged,true);assert.equal(e.events.length,1)});
test('Different existing public link cannot be silently replaced by observation',async()=>{const e=setup();e.db.tables.contacts[0].facebook_profile_url='https://www.facebook.com/customerOriginal';const r=await post(e);assert.equal(r.status,409);assert.equal(e.db.tables.contacts[0].facebook_profile_url,'https://www.facebook.com/customerOriginal')});
test('Same-origin signed-in web request is compatible',async()=>{assert.equal((await post(setup(),payload,{bearer:false})).status,200)});
for(const [label,options] of [['revoked',{denied:true}],['permission',{permissionDenied:true}],['expired cookie subscription',{expired:true}]])test(label+' cannot save public profile',async()=>{const e=setup(options);assert.ok((await post(e,payload,{bearer:!options.expired})).status>=400);assert.equal(e.db.tables.contacts[0].facebook_profile_url,null)});
for(const origin of [null,'https://evil.test','https://app.tenhchat.com.evil.test'])test('Cookie profile sync refuses origin '+origin,async()=>{assert.equal((await post(setup(),payload,{bearer:false,origin})).status,403)});
for(const url of ['javascript:alert(1)','https://facebook.com.evil.test/person','https://www.facebook.com/me','https://www.facebook.com/profile.php?id='+psid,'https://www.facebook.com/profile.php?id='+pageId,'https://user:secret@www.facebook.com/customer','https://www.facebook.com/profile.php?id=12&id=34','https://business.facebook.com/latest/inbox/all'])test('Reject invalid or scoped profile '+url,async()=>{const e=setup();assert.equal((await post(e,{...payload,publicProfileUrl:url})).status,400);assert.equal(e.events.length,0)});
for(const body of [null,[],{}, {...payload,psid:Number(psid)}, {...payload,pageId:123}, {...payload,conversationId:'NOT_UUID'}, {...payload,businessId:'other'}, {...payload,expectedUpdatedAt:'stale'}])test('Malformed or stale input denied '+JSON.stringify(body),async()=>{const r=await post(setup(),body);assert.ok(r.status>=400)});
test('Two Pages with same PSID require Page context',async()=>{const e=setup();e.db.tables.social_accounts.push({...e.db.tables.social_accounts[0],id:'s2',platform_account_id:'555'});e.db.tables.conversations.push({...e.db.tables.conversations[0],id:'22222222-2222-4222-8222-222222222222',social_account_id:'s2'});assert.equal((await post(e,{psid,publicProfileUrl})).status,409);assert.equal((await post(e,payload)).status,200)});
test('Inactive/wrong Page never associates profile',async()=>{const e=setup();e.db.tables.social_accounts[0].is_active=false;assert.equal((await post(e)).status,403)});
test('Another workspace cannot be written using supplied businessId',async()=>{const e=setup();assert.equal((await post(e,{...payload,businessId:'b2'})).status,403)});
test('Storage failure not reported as success',async()=>{const e=setup();e.db.failures.push({table:'contacts',op:'update'});assert.equal((await post(e)).status,500);assert.equal(e.events.length,0)});
test('No unseen customer created from extension-supplied ID',async()=>{const e=setup();assert.equal((await post(e,{...payload,psid:'777'})).status,404);assert.equal(e.db.tables.contacts.length,1)});
test('Page Messenger fallback explicitly separate from public profile',()=>{const {facebookCustomerLinks}=setup().load('lib/facebook/customer-navigation.ts');assert.equal(facebookCustomerLinks('abc','123'),null);const result=facebookCustomerLinks(pageId,psid);assert.equal(new URL(result.businessSuiteUrl).searchParams.get('selected_item_id'),psid);assert.equal(new URL(result.pageMessengerUrl).hostname,'m.me');assert.ok(!result.publicProfileUrl)});
