const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{test}=require('node:test'),assert=require('node:assert/strict');const {ROOT}=require('./harness.cjs');
const base='tenh-extension/src/';const helpers=fs.readFileSync(path.join(ROOT,base+'profile-sync-helpers.js'),'utf8');const worker=fs.readFileSync(path.join(ROOT,base+'profile-sync-worker.js'),'utf8').replace(/^import .*;$/mg,'').replace('export function','function');
const url='https://business.facebook.com/latest/inbox/all/?asset_id=123&selected_item_id=456&thread_type=FB_MESSAGE',publicUrl='https://www.facebook.com/profile.php?id=999';
function runtime(options={}){const ctx={URL,Map,Date};vm.runInNewContext(helpers+'\n'+worker+'\nglobalThis.make=createProfileSyncHandler;',ctx);const calls=[],notifications=[],statuses=[];const fn=ctx.make({extensionId:'ext',getState:async()=>({token:'test-token',...(options.state||{})}),getTab:async()=>({url:options.currentUrl||url}),callTenh:async(path,init)=>{calls.push({path,init});if(options.throw)throw new Error('network');await new Promise(r=>setTimeout(r,1));return options.response||{ok:true,result:{success:true,psid:'456',pageId:'123',publicProfileUrl:publicUrl,conversationId:'conv1'}}},notify:async event=>notifications.push(event),status:async value=>statuses.push(value)});return {fn,helpers:ctx.TenhProfileSyncHelpers,calls,notifications,statuses};}
const message={type:'FB_PROFILE_URL_OBSERVED',psid:'456',pageId:'123',publicProfileUrl:publicUrl};const sender={id:'ext',frameId:0,tab:{id:1,url},url};
test('Passive sync uses existing device credential and receiver',async()=>{const e=runtime();const r=await e.fn(message,sender);assert.equal(r.saved,true);assert.equal(e.calls[0].path,'/api/save-profile-url');assert.equal(e.calls[0].init.token,'test-token');assert.equal(e.notifications[0].type,'customer.profile.updated');assert.equal(e.notifications[0].publicProfileUrl,undefined)});
test('Concurrent identical observations make one write',async()=>{const e=runtime();const results=await Promise.all([e.fn(message,sender),e.fn(message,sender)]);assert.ok(results.every(r=>r.saved));assert.equal(e.calls.length,1);await e.fn(message,sender);assert.equal(e.calls.length,1)});
for(const s of [{...sender,id:'evil'},{...sender,frameId:1},{...sender,url:'https://evil.test'},{...sender,url:url.replace('123','122')},{...sender,url:url.replace('456','457')},{...sender,tab:{id:null,url}}])test('Reject forged sender '+JSON.stringify(s),async()=>{const e=runtime();assert.equal((await e.fn(message,s)).saved,false);assert.equal(e.calls.length,0)});
for(const [name,opts] of [['sign-in',{state:{token:null}}],['optout',{state:{profileSyncEnabled:false}}],['stale Page',{currentUrl:url.replace('123','124')}],['stale conversation',{currentUrl:url.replace('456','457')}]])test(name+' stops before saving',async()=>{const e=runtime(opts);assert.equal((await e.fn(message,sender)).saved,false);assert.equal(e.calls.length,0)});
test('Receiver error is not turned into profile available',async()=>{const e=runtime({response:{ok:false,status:403,result:{code:'permission_denied'}}});assert.equal((await e.fn(message,sender)).reason,'permission_denied');assert.equal(e.notifications.length,0)});
test('Response Page mismatch is not accepted',async()=>{const e=runtime({response:{ok:true,result:{success:true,pageId:'000',psid:'456',publicProfileUrl:publicUrl}}});assert.equal((await e.fn(message,sender)).saved,false)});
test('Network exception is contained',async()=>{const e=runtime({throw:true});assert.equal((await e.fn(message,sender)).reason,'profile_sync_network_unavailable')});
for(const input of ['javascript:alert(1)','https://www.facebook.com/me','https://www.facebook.com/profile.php?id=456','https://www.facebook.com/profile.php?id=123','https://www.facebook.com/profile.php?id=1&id=2','https://www.facebook.com.evil.test/user','https://business.facebook.com/latest/inbox/all','https://www.facebook.com/settings'])test('Profile validator refuses '+input,()=>assert.equal(runtime().helpers.profile(input,{pageId:'123',psid:'456'}),null));
test('Wrapped public URL normalizes without visiting it',()=>{assert.equal(runtime().helpers.profile('https://l.facebook.com/l.php?u='+encodeURIComponent(publicUrl),{pageId:'123',psid:'456'}),publicUrl)});
for(const input of [url.replace('FB_MESSAGE','IG_MESSAGE'),url+'&asset_id=999','https://www.facebook.com/profile.php?id=123',url.replace('456','uuid-local')])test('Invalid thread context '+input,()=>assert.equal(runtime().helpers.context(input),null));
test('Visible DOM observer has no click, cookies or direct fetch logic',()=>{const src=fs.readFileSync(path.join(ROOT,base+'profile-sync.js'),'utf8');assert.ok(!/\.click\(|document\.cookie|\bfetch\(/.test(src));assert.match(src,/profile_sync_timeout/);assert.match(src,/attempted\.set/)});
