const {test}=require('node:test'),assert=require('node:assert/strict');const {setup,CONV}=require('./harness.cjs');
const server='lib/stickers/stipop-server.ts';const image='https://img.stipop.io/test.png',PNG=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,13]);
function mediaFetch(url,init){return String(url).includes('/analytics/')?new Response(JSON.stringify({header:{code:'0000'}})):new Response(PNG,{headers:{'Content-Type':'image/png'}})}
function selection(e,extra={}){return {businessId:'b1',conversationId:CONV,memberId:'m1',pageId:e.scope.page.platform_account_id,psid:e.scope.contact.platform_user_id,stickerId:'123',imageUrl:image,label:'Hello',query:'hello',expiresAt:Date.now()+60000,...extra};}
function sendBody(e,extra={}){return {conversationId:CONV,requestId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',selectionToken:e.load(server).signSelection(selection(e)),...extra};}
async function send(e,body=sendBody(e),opts={}){const r=await e.load('app/api/stickers/send/route.ts').POST(e.request(body,opts));return {status:r.status,data:await r.json()};}
test('Stipop catalog searches vendor with per-agent identity and no exposed API key',async()=>{const e=setup(),s=e.load(server);const result=await s.searchStickers(e.scope,'hello');assert.equal(result.stickers.length,1);assert.equal(result.stickers[0].provider,'stipop');assert.equal(e.calls[0].init.headers.apikey,e.env.STIPOP_API_KEY);assert.equal(new URL(e.calls[0].url).searchParams.get('limit'),'24');assert.ok(!JSON.stringify(result).includes(e.env.STIPOP_API_KEY));assert.ok(s.verifySelection(result.stickers[0].selectionToken,e.scope))});
test('Different agents get distinct vendor userIds',async()=>{const e=setup(),s=e.load(server);await s.searchStickers(e.scope,'hello');await s.searchStickers({...e.scope,member:{...e.scope.member,user_id:'u2',id:'m2'}},'hello');assert.notEqual(new URL(e.calls[0].url).searchParams.get('userId'),new URL(e.calls[1].url).searchParams.get('userId'))});
test('Short cache avoids repeated vendor search and keeps scope-bound selection',async()=>{const e=setup(),s=e.load(server);await s.searchStickers(e.scope,'hello');await s.searchStickers(e.scope,'hello');assert.equal(e.calls.length,1)});
test('Missing API key fails clearly without replacing local stickers',async()=>{const e=setup({env:{STIPOP_API_KEY:''}});await assert.rejects(e.load(server).searchStickers(e.scope,'hello'),x=>x.code==='STICKER_STORE_NOT_CONFIGURED');assert.equal(e.calls.length,0)});
for(const input of ['http://img.stipop.io/test.png','https://evil.test/file','https://stipop.io.evil.test/file','https://127.0.0.1/file','https://localhost/file','https://img.stipop.io:8443/file','https://x:y@img.stipop.io/file','data:image/png;base64,a'])test('Reject unapproved media '+input,()=>assert.equal(setup().load(server).stickerMediaUrl(input),null));
test('Optional exact CDN allowlist does not allow suffix lookalikes',()=>{const s=setup({env:{STIPOP_MEDIA_HOSTS:'cdn.vendor.test'}}).load(server);assert.ok(s.stickerMediaUrl('https://cdn.vendor.test/a.png'));assert.equal(s.stickerMediaUrl('https://cdn.vendor.test.evil/a.png'),null)});
for(const patch of [{conversationId:'other'},{businessId:'b2'},{memberId:'m2'},{pageId:'different'},{psid:'other'}])test('Signed selection is bound to '+Object.keys(patch)[0],()=>{const e=setup(),s=e.load(server),token=s.signSelection(selection(e,patch));assert.throws(()=>s.verifySelection(token,e.scope))});
test('Modified HMAC and expired selections refused',()=>{const e=setup(),s=e.load(server),token=s.signSelection(selection(e));assert.throws(()=>s.verifySelection(token.slice(0,-4)+'abcd',e.scope));assert.throws(()=>s.verifySelection(s.signSelection(selection(e,{expiresAt:Date.now()-1})),e.scope))});
test('Malformed vendor response refuses catalog',async()=>{const e=setup({fetch:async()=>new Response('<html>error</html>')});await assert.rejects(e.load(server).searchStickers(e.scope,'hello'))});
test('Vendor only malicious result URL refuses catalog',async()=>{const e=setup({fetch:async()=>new Response(JSON.stringify({header:{code:'0000'},body:{stickerList:[{stickerId:1,stickerImg:'https://evil.test/image'}]}}))});await assert.rejects(e.load(server).searchStickers(e.scope,'hello'))});
for(const code of [401,429,500])test('Vendor status '+code+' is not success',async()=>{const e=setup({fetch:async()=>new Response('{}',{status:code})});await assert.rejects(e.load(server).searchStickers(e.scope,'hello'))});
test('Vendor transport fails safely',async()=>{const e=setup({fetch:async()=>{throw new Error('offline')}});await assert.rejects(e.load(server).searchStickers(e.scope,'hello'))});
test('Authenticated GET searches selected conversation only',async()=>{const e=setup(),r=await e.load('app/api/stickers/search/route.ts').GET(e.request(null,{method:'GET',path:'/api/stickers/search?conversationId='+CONV+'&q=hello'}));assert.equal(r.status,200);assert.equal((await r.json()).success,true)});
test('GET cannot access another conversation',async()=>{const e=setup(),r=await e.load('app/api/stickers/search/route.ts').GET(e.request(null,{method:'GET',path:'/api/stickers/search?conversationId=other'}));assert.equal(r.status,403);assert.equal(e.calls.length,0)});
test('Content is validated before passing file into existing attachment endpoint',async()=>{const e=setup({fetch:mediaFetch}),s=e.load(server),file=await s.downloadSticker(selection(e));assert.equal(file.type,'image/png');assert.equal(file.size,PNG.length);assert.equal(e.calls[0].init.redirect,'error')});
for(const [kind,body,headers] of [['HTML MIME','<html>',{'content-type':'text/html'}],['HTML spoofing PNG','<html>',{'content-type':'image/png'}],['oversize',PNG,{'content-type':'image/png','content-length':String(9*1024*1024)}],['empty','',{'content-type':'image/png'}]])test('Download rejects '+kind,async()=>{const e=setup({fetch:async()=>new Response(body,{headers})});await assert.rejects(e.load(server).downloadSticker(selection(e)))});
test('Send adapter calls existing attachment path once and persists completed receipt',async()=>{const e=setup({fetch:mediaFetch}),r=await send(e);assert.equal(r.status,200);assert.equal(r.data.delivery,'image_attachment');assert.equal(e.dispatches.length,1);const f=e.dispatches[0].form;assert.equal(f.get('conversationId'),CONV);assert.equal(f.get('recipientId'),e.scope.contact.platform_user_id);assert.equal(f.get('kind'),'image');assert.ok(f.get('file') instanceof File);assert.match(f.get('clientRequestId'),/^optimistic:attachment:/);assert.equal(e.db.tables.facebook_sticker_sends[0].status,'completed')});
test('Retry same request returns previous result and never dispatches twice',async()=>{const e=setup({fetch:mediaFetch}),body=sendBody(e);await send(e,body);await send(e,body);assert.equal(e.dispatches.length,1)});
test('Same UUID with different sticker rejects rather than confusing receipts',async()=>{const e=setup({fetch:mediaFetch}),body=sendBody(e);await send(e,body);const second={...body,selectionToken:e.load(server).signSelection(selection(e,{stickerId:'124',imageUrl:'https://img.stipop.io/another.png'}))};assert.equal((await send(e,second)).status,409);assert.equal(e.dispatches.length,1)});
test('Concurrent duplicate requests have one durable insert winner',async()=>{const e=setup({fetch:mediaFetch}),body=sendBody(e);e.db.failures.push({table:'facebook_sticker_sends',op:'insert',code:'23505',when:q=>e.db.tables.facebook_sticker_sends.some(row=>row.request_id===q.body.request_id&&row.business_id===q.body.business_id)});const r=await Promise.all([send(e,body),send(e,body)]);assert.equal(e.dispatches.length,1);assert.equal(r.filter(x=>x.status===200).length,1)});
for(const [label,options] of [['expired window',{windowState:'expired'}],['blocked',{blocked:true}],['no send permission',{permissionDenied:true}],['workspace denied',{denied:true}]])test(label+' never dispatches sticker',async()=>{const e=setup({...options,fetch:mediaFetch}),r=await send(e);assert.ok(r.status>=400);assert.equal(e.dispatches.length,0)});
test('Missing receipt migration never dispatches',async()=>{const e=setup({fetch:mediaFetch});delete e.db.tables.facebook_sticker_sends;assert.equal((await send(e)).data.code,'STICKER_STORAGE_REQUIRED');assert.equal(e.dispatches.length,0)});
for(const opts of [{origin:'https://evil.test'},{origin:null}])test('CSRF rejected '+JSON.stringify(opts),async()=>{const e=setup({fetch:mediaFetch});assert.equal((await send(e,sendBody(e),opts)).status,403);assert.equal(e.dispatches.length,0)});
for(const options of [{delegateThrow:true},{delegateResult:{success:false,error:'Provider ambiguous'},delegateStatus:502}])test('Uncertain delegate outcome disables automatic resend '+JSON.stringify(options),async()=>{const e=setup({...options,fetch:mediaFetch}),body=sendBody(e);assert.ok((await send(e,body)).status>=400);assert.equal(e.db.tables.facebook_sticker_sends[0].status,'uncertain');await send(e,body);assert.equal(e.dispatches.length,1)});
test('Successful provider send plus receipt write failure still never silently retries',async()=>{const e=setup({fetch:mediaFetch}),body=sendBody(e);e.db.failures.push({table:'facebook_sticker_sends',op:'update'});const r=await send(e,body);assert.equal(r.data.success,true);assert.ok(r.data.warning);await send(e,body);assert.equal(e.dispatches.length,1)});
test('Failed noncritical vendor analytics do not change send into failure',async()=>{const e=setup({fetch:async url=>String(url).includes('analytics')?new Response('{}',{status:500}):new Response(PNG,{headers:{'content-type':'image/png'}})});assert.equal((await send(e)).data.success,true);assert.equal(e.dispatches.length,1)});
