"use client";
import { useEffect, useRef, useState } from "react";
import { DRAFT_KINDS, parseDraftRules, parseDraftEvents, type DraftKind, type DraftRule, type DraftEvent, type DraftAction } from "@/lib/bot/draft-rules";
import { useBotPreviewRegistration } from "@/components/bot/bot-messenger-preview";
import { useBotSaveRegistration, type BotSaveResult } from "@/components/bot/bot-save-toolbar";
import { useBotEditorField } from "@/lib/bot/use-editor-field";
type Context={businessId:string;canManage:boolean;pages:{id:string;account_name:string|null;platform:string;platform_account_id?:string;recordedConnectionStatus?:string}[];members:{id:string;full_name:string|null}[]};
const labels:Record<DraftKind,string>={welcome_away:"Welcome / Away",keyword_faq:"Keyword FAQ",human_takeover:"Autoassign / Human takeover",unanswered_alert:"Unanswered staff alert",conversation_menu:"Conversation menu",ads_specific_reply:"Ads-specific reply",returning_context:"Returning customer context",connection_health:"Recorded connection health",comment_phone_spam_hide:"Comment phone / spam hide",comment_filters:"Comment keyword / first-level filters",qr_ref_flow:"QR / reference URL flow",conditional_followups:"Cancellable conditional follow-ups"};
const field="mt-1 min-w-0 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm";
export function BotDraftSettings({selectedKind}:{selectedKind?:DraftKind}={}){
  const [localKind,setKind]=useState<DraftKind>("welcome_away");
  const kind=selectedKind??localKind;
  const [context,setContext]=useState<Context|null>(null),[error,setError]=useState(""),[channel,setChannel]=useState(""),[rules,setRules]=useState<DraftRule[]>([]);
  const [name,setName]=useBotEditorField(kind,""),[template,setTemplate]=useBotEditorField(kind,""),[away,setAway]=useBotEditorField(kind,""),[keywords,setKeywords]=useBotEditorField(kind,""),[member,setMember]=useBotEditorField(kind,"");
  const [timezone,setTimezone]=useBotEditorField(kind,()=>Intl.DateTimeFormat().resolvedOptions().timeZone??"UTC"),[start,setStart]=useBotEditorField(kind,"09:00"),[end,setEnd]=useBotEditorField(kind,"17:00"),[priority,setPriority]=useBotEditorField(kind,50),[cooldown,setCooldown]=useBotEditorField(kind,60),[alertMinutes,setAlertMinutes]=useBotEditorField(kind,15),[assign,setAssign]=useBotEditorField(kind,true);
  const [adIds,setAdIds]=useBotEditorField(kind,""),[excludes,setExcludes]=useBotEditorField(kind,""),[firstLevel,setFirstLevel]=useBotEditorField(kind,true),[phoneOnly,setPhoneOnly]=useBotEditorField(kind,false),[minPrevious,setMinPrevious]=useBotEditorField(kind,1),[refToken,setRefToken]=useBotEditorField(kind,"campaign_welcome");
  const [steps,setSteps]=useBotEditorField(kind,""),[cancelKeywords,setCancelKeywords]=useBotEditorField(kind,"stop,cancel"),[respectHours,setRespectHours]=useBotEditorField(kind,true);
  const [sampleAd,setSampleAd]=useBotEditorField(kind,""),[samplePrevious,setSamplePrevious]=useBotEditorField(kind,0),[sampleLastSeen,setSampleLastSeen]=useBotEditorField(kind,()=>new Date(Date.now()-86400000).toISOString().slice(0,16)),[sampleRef,setSampleRef]=useBotEditorField(kind,"campaign_welcome");
  const [samplePost,setSamplePost]=useBotEditorField(kind,""),[sampleComment,setSampleComment]=useBotEditorField(kind,""),[sampleParent,setSampleParent]=useBotEditorField(kind,"first"),[sampleDeleted,setSampleDeleted]=useBotEditorField(kind,false);
  const [menu,setMenu]=useBotEditorField(kind,""),[events,setEvents]=useBotEditorField<DraftEvent[]>(kind,[]),[result,setResult]=useBotEditorField<DraftAction[]|null>(kind,null),[busy,setBusy]=useState(false);
  const [eventKind,setEventKind]=useBotEditorField<DraftEvent["kind"]>(kind,"customer"),[eventText,setEventText]=useBotEditorField(kind,""),[firstContact,setFirstContact]=useBotEditorField(kind,false),[eventAt,setEventAt]=useBotEditorField(kind,()=>new Date().toISOString().slice(0,16));
  useEffect(()=>{const abort=new AbortController();void fetch("/api/facebook/auto-reply?scope=drafts",{signal:abort.signal,cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error??"Drafts unavailable");setContext(data);}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort();},[]);
  const [revision,setRevision]=useState<number|null>(null),[storageBusy,setStorageBusy]=useState(false),[storageNote,setStorageNote]=useState("");
  const [savedRules,setSavedRules]=useState("[]");
  const [history,setHistory]=useState<{id:string;status:string;reason:string|null;action:{kind:string;ruleKind?:string;text?:string;url?:string};rule_id?:string}[]|null>(null);
  const scopeRef=useRef({key:"",epoch:0});
  const [unfinishedKinds,setUnfinishedKinds]=useState<Set<DraftKind>>(()=>new Set());
  const reset=()=>{setUnfinishedKinds(new Set());setRules([]);setEvents([]);setResult(null);setHistory(null);};
  useEffect(()=>{
    scopeRef.current={key:(context?.businessId??"")+":"+channel,epoch:scopeRef.current.epoch+1};
    if(!channel||!context?.businessId)return;
    const abort=new AbortController(),scope=context.businessId+":"+channel;
    void Promise.resolve().then(()=>{if(abort.signal.aborted)return;setRevision(null);setStorageNote("");setStorageBusy(true);return fetch("/api/tenh-bot/rules?channelId="+encodeURIComponent(channel),{signal:abort.signal,cache:"no-store"});})
      .then(async response=>{if(!response)return;const data=await response.json();if(!response.ok)throw Error(data.error??"Saved rules unavailable.");
        if(abort.signal.aborted||scopeRef.current.key!==scope)return;
        const saved=data.rules.length?parseDraftRules(data.rules,{businessId:context.businessId,channelId:channel}):[];
        if(!Number.isSafeInteger(data.revision)||data.revision<0)throw Error("Saved revision unavailable.");
        setRules(saved);setSavedRules(JSON.stringify(saved));setRevision(data.revision);setStorageNote("Saved rules loaded. All disabled.");})
      .catch(error=>{if(!abort.signal.aborted&&scopeRef.current.key===scope)setStorageNote(error.message);})
      .finally(()=>{if(!abort.signal.aborted&&scopeRef.current.key===scope)setStorageBusy(false);});
    return()=>abort.abort();
  },[channel,context?.businessId]);
  async function loadHistory(){
    if(!channel||storageBusy)return;const scope=scopeRef.current.key,epoch=scopeRef.current.epoch;setStorageBusy(true);
    try{const response=await fetch("/api/tenh-bot/history?channelId="+encodeURIComponent(channel),{cache:"no-store"});const data=await response.json();
      if(scopeRef.current.key!==scope||scopeRef.current.epoch!==epoch)return;
      if(!response.ok)throw Error(data.error??"Execution history unavailable.");setHistory(data.jobs);
    }catch(error){if(scopeRef.current.key===scope&&scopeRef.current.epoch===epoch)setStorageNote((error as Error).message);}
    finally{if(scopeRef.current.key===scope&&scopeRef.current.epoch===epoch)setStorageBusy(false);}
  }
  async function save():Promise<BotSaveResult>{
    if(!context?.canManage||revision===null||storageBusy)return {ok:false,message:"Choose an authorized Page and wait for its saved rules to load."};
    const scope=scopeRef.current.key,epoch=scopeRef.current.epoch;setStorageBusy(true);setStorageNote("");
    try{const response=await fetch("/api/tenh-bot/rules",{method:"POST",headers:{"Content-Type":"application/json"},
      body:JSON.stringify({channelId:channel,revision,rules,enabled:false})});const data=await response.json();
      if(scopeRef.current.key!==scope||scopeRef.current.epoch!==epoch)return {ok:false,message:"Page changed before save confirmation."};
      if(!response.ok)throw Error(data.error??"Save failed.");
      setRevision(data.revision);setSavedRules(JSON.stringify(rules));setStorageNote("Saved to database. All rules remain disabled; no actions executed.");return {ok:true,message:"Page Bot rules saved disabled."};
    }catch(error){if(scopeRef.current.key===scope&&scopeRef.current.epoch===epoch)setStorageNote((error as Error).message);return {ok:false,message:(error as Error).message};}
    finally{if(scopeRef.current.key===scope&&scopeRef.current.epoch===epoch)setStorageBusy(false);}
  }
  useEffect(()=>{const dirty=JSON.stringify(rules)!==savedRules||unfinishedKinds.size>0;if(!dirty)return;const prevent=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",prevent);return()=>window.removeEventListener("beforeunload",prevent);},[rules,savedRules,unfinishedKinds]);
  function clearCurrent(){if(!selectedKind){reset();return;}setUnfinishedKinds(current=>new Set([...current].filter(value=>value!==selectedKind)));setRules(current=>current.filter(rule=>rule.kind!==selectedKind));setEvents([]);setResult(null);setHistory(null);}
  function add(){if(!context)return;setError("");const minutes=(s:string)=>{const [h,m]=s.split(":").map(Number);return h*60+m;};
    const list=(value:string)=>value.split(",").map(x=>x.trim()).filter(Boolean);
    const options:DraftRule["options"]={};
    if(kind==="ads_specific_reply")options.adIds=list(adIds);
    if(kind==="returning_context")options.minPrevious=minPrevious;
    if(kind==="comment_phone_spam_hide"||kind==="comment_filters"){options.excludeKeywords=list(excludes);options.firstLevelOnly=firstLevel;}
    if(kind==="comment_phone_spam_hide")options.phoneOnly=phoneOnly;
    if(kind==="qr_ref_flow")options.refToken=refToken;
    if(kind==="conditional_followups"){options.cancelKeywords=list(cancelKeywords);options.respectHours=respectHours;options.steps=steps.split("\n").filter(x=>x.trim()).map(line=>{const split=line.indexOf("|");return {delayMinutes:split<0?NaN:Number(line.slice(0,split).trim()),template:split<0?"":line.slice(split+1).trim()};});}
    const rule:DraftRule={id:crypto.randomUUID(),options,mode:"draft",businessId:context.businessId,channelId:channel,kind,name,template,awayTemplate:away,keywords:keywords.split(",").map(x=>x.trim()).filter(Boolean),timezone,hours:[1,2,3,4,5].map(day=>({day,start:minutes(start),end:minutes(end)===0?1440:minutes(end)})),priority,cooldownMinutes:cooldown,memberIds:(["human_takeover","unanswered_alert"].includes(kind)&&member)?[member]:[],assignOnIncoming:assign,alertMinutes,menu:menu.split("\n").filter(x=>x.trim()).map(row=>{const split=row.indexOf("|");return {label:row.slice(0,split).trim(),reply:row.slice(split+1).trim()};})};
    try{if(kind==="conversation_menu"&&menu.split("\n").filter(x=>x.trim()).some(x=>!x.includes("|")))throw Error("Separate each menu label and reply with |.");parseDraftRules([...rules,rule],{businessId:context.businessId,channelId:channel});setRules(current=>[...current,rule]);setUnfinishedKinds(current=>new Set([...current].filter(value=>value!==kind)));setResult(null);}catch(e){setError((e as Error).message)}
  }
  function addEvent(){if(!context||!channel)return;setError("");try{
    const event:DraftEvent={id:crypto.randomUUID(),businessId:context.businessId,channelId:channel,conversationId:"sample-conversation",recipientId:"sample-customer",kind:eventKind,at:new Date(eventAt+"Z").toISOString(),text:eventText,firstContact};
    if(eventKind==="customer"&&sampleAd.trim())event.source={kind:"simulated_ad_referral",adId:sampleAd.trim()};
    if(eventKind==="customer"&&samplePrevious>0)event.returning={previousConversations:samplePrevious,lastSeenAt:new Date(sampleLastSeen+"Z").toISOString()};
    if(eventKind==="comment")event.comment={postId:samplePost,commentId:sampleComment,parentId:sampleParent==="first"?samplePost:sampleParent==="nested"?sampleComment:null,deleted:sampleDeleted};
    if(eventKind==="referral"||(eventKind==="customer"&&kind==="qr_ref_flow"))event.refToken=sampleRef;
    parseDraftEvents([...events,event],{businessId:context.businessId,channelId:channel},true);setEvents(current=>[...current,event]);setResult(null);
  }catch(e){setError((e as Error).message)}}
  async function test(){setBusy(true);setError("");setResult(null);try{const response=await fetch("/api/facebook/auto-reply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"draftPreview",channelId:channel,rules:rules.filter(rule=>!selectedKind||rule.kind===selectedKind),events,now:new Date().toISOString()})});if(!response)return;const data=await response.json();if(!response.ok)throw Error(data.error);setResult(data.actions);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const rulesDirty=JSON.stringify(rules)!==savedRules;
  const sharedSave=useBotSaveRegistration("modern",{dirty:rulesDirty||unfinishedKinds.size>0,busy:storageBusy||busy,
    canSave:Boolean(context?.canManage&&revision!==null&&channel&&!storageBusy&&!busy&&rulesDirty&&!unfinishedKinds.size),
    message:!context?.canManage?"Channel management permission is required.":!channel?"Choose a Page to save rules.":revision===null?"Wait for saved Page rules to load.":unfinishedKinds.size?"Add unfinished form edits as rules before saving; each Bot keeps its fields.":storageNote},save);
  const internalDescriptions:Partial<Record<DraftKind,string>>={human_takeover:"Staff assignment and human hold are internal actions, not customer messages.",unanswered_alert:"The proposed alert is for staff. It is not a Messenger reply.",connection_health:"Recorded Page connection status appears in the internal test plan; no live probe is performed.",comment_phone_spam_hide:"Matching comments may be proposed for hiding. No comments are hidden by this preview.",comment_filters:"Comment inclusion, exclusion and first-level conditions are internal filter results.",returning_context:"Prior-conversation context is an internal result. A reply is shown only when a template is configured."};
  useBotPreviewRegistration("modern",{kind,channel:context?.pages.find(page=>page.id===channel)?.account_name??"",customerText:eventText,
    reply:internalDescriptions[kind]&&kind!=="returning_context"?"":kind==="conversation_menu"?menu.split("\n").filter(Boolean).map(row=>row.split("|")[0]).join("\n"):kind==="conditional_followups"?steps.split("\n")[0]?.split("|").slice(1).join("|")??"":template,
    away:kind==="welcome_away"?away:undefined,internal:internalDescriptions[kind],outcomes:result??undefined});
  return <section className="space-y-5 bg-white" aria-labelledby="bot-drafts-heading">
    <h2 id="bot-drafts-heading" className={selectedKind?"sr-only":"text-xl font-semibold"}>{selectedKind?labels[selectedKind]:"Bot configurations"}</h2>
    <p className="text-sm text-slate-600">Configure disabled rules for your Page. Add each rule, then save all changes. Tests use sample data and never contact customers.</p>
    {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
    {context&&!context.canManage&&<p className="text-sm text-slate-500">Read-only. Channel management permission is required to edit rules.</p>}
    <fieldset onChangeCapture={event=>{const target=event.target as HTMLElement;if(target.getAttribute("data-bot-scope")!=="channel"&&target.getAttribute("data-bot-scope")!=="kind"){setUnfinishedKinds(current=>new Set(current).add(kind));setResult(null);}}} disabled={!context?.canManage||busy||storageBusy} className="grid gap-4 disabled:opacity-60 sm:grid-cols-2">
      <div className="sm:col-span-2"><h3 className="text-sm font-semibold text-slate-900">Page &amp; rule basics</h3></div>
      <label className="text-sm">Connected channel<select data-bot-scope="channel" className={field} value={channel} onChange={e=>{if((JSON.stringify(rules)!==savedRules||unfinishedKinds.size>0)&&!window.confirm("Switch channel and replace unsaved rules? Stay to save them first."))return;scopeRef.current={key:(context?.businessId??"")+":"+e.target.value,epoch:scopeRef.current.epoch+1};setRevision(null);setStorageBusy(Boolean(e.target.value));setChannel(e.target.value);reset();const page=context?.pages.find(p=>p.id===e.target.value)?.platform_account_id;setSamplePost(page?`${page}_456`:"");setSampleComment(page?`${page}_789`:"");}}><option value="">Choose a Facebook Page</option>{context?.pages.map(p=><option key={p.id} value={p.id} disabled={p.platform!=="facebook"}>{p.account_name??p.id}{p.platform!=="facebook"?" · unavailable":" · draft only"}</option>)}</select></label>
      {!selectedKind&&<label className="text-sm">Draft type<select data-bot-scope="kind" className={field} value={kind} onChange={e=>setKind(e.target.value as DraftKind)}>{DRAFT_KINDS.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>}
      <label className="text-sm">Name<input className={field} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label>
      <div className="border-t border-slate-200 pt-4 sm:col-span-2"><h3 className="text-sm font-semibold text-slate-900">Conditions &amp; timing</h3></div>
      <label className="text-sm">Keywords / menu command (comma separated)<input className={field} value={keywords} onChange={e=>setKeywords(e.target.value)}/></label>
      {(kind==="welcome_away"||kind==="conditional_followups")&&<><label className="text-sm">Business timezone<input className={field} value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><div className="flex gap-2"><label className="text-sm">Monday–Friday opens<input type="time" className={field} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="min-w-0 text-sm">Closes<input type="time" className={field} value={end} onChange={e=>setEnd(e.target.value)}/></label></div></>}
      {kind==="ads_specific_reply"&&<label className="text-sm sm:col-span-2">Explicit public Ad IDs (comma separated)<input className={field} value={adIds} onChange={e=>setAdIds(e.target.value)}/><span className="text-xs text-slate-500">Exact synthetic referral matching only; live Ad ownership is unverified. Never derive an Ad ID from a customer ID or text.</span></label>}
      {kind==="returning_context"&&<label className="text-sm">Minimum previous conversations<input className={field} type="number" min={1} max={10000} value={minPrevious} onChange={e=>setMinPrevious(Number(e.target.value))}/><span className="text-xs text-slate-500">Synthetic counts only; no real history is fetched. Reply template is optional.</span></label>}
      {kind==="connection_health"&&<p className="text-sm text-slate-600">Recorded selected-channel status: {context?.pages.find(p=>p.id===channel)?.recordedConnectionStatus??"unknown"}. A health sample previews stored metadata, not a live probe or proof of send permission.</p>}
      {(kind==="comment_phone_spam_hide"||kind==="comment_filters")&&<><label className="text-sm">Exclude comment keywords (comma separated)<input className={field} value={excludes} onChange={e=>setExcludes(e.target.value)}/></label><label className="text-sm"><input type="checkbox" checked={firstLevel} onChange={e=>setFirstLevel(e.target.checked)}/> First-level only; missing parent never counts as first-level.</label></>}
      {kind==="comment_phone_spam_hide"&&<label className="text-sm"><input type="checkbox" checked={phoneOnly} onChange={e=>setPhoneOnly(e.target.checked)}/> Explicitly propose phone-only hiding without a spam keyword. Manual review required; no comments are hidden or deleted.</label>}
      {kind==="qr_ref_flow"&&<label className="text-sm sm:col-span-2">Public campaign reference<input className={field} maxLength={50} value={refToken} onChange={e=>setRefToken(e.target.value)}/><span className="text-xs text-slate-500">Use campaign_word, letters only. Link / QR payload proposal uses only the selected public Page ID and label. No customer data or redirects. QR image export and live referral activation unavailable.</span></label>}
      {kind==="conditional_followups"&&<><label className="text-sm sm:col-span-2">Follow-up steps: minutes after previous step | template<textarea className={field} value={steps} onChange={e=>setSteps(e.target.value)}/><span className="text-xs text-slate-500">Maximum five steps. Unanswered direct conversation only. New customer/staff/operator events cancel pending plans; expired or out-of-hours steps are skipped, never backfilled.</span></label><label className="text-sm">Cancel keywords (comma separated)<input className={field} value={cancelKeywords} onChange={e=>setCancelKeywords(e.target.value)}/></label><label className="text-sm"><input type="checkbox" checked={respectHours} onChange={e=>setRespectHours(e.target.checked)}/> Require configured timezone/business hours.</label></>}
      {kind==="conversation_menu"&&<label className="text-sm sm:col-span-2">Choices: one Label | Reply per line<textarea className={field} value={menu} onChange={e=>setMenu(e.target.value)}/><span className="text-xs text-slate-500">Text-choice preview; provider quick-reply buttons are unavailable.</span></label>}
      {(kind==="human_takeover"||kind==="unanswered_alert")&&<label className="text-sm">Existing workspace staff<select className={field} value={member} onChange={e=>setMember(e.target.value)}><option value="">Choose staff</option>{context?.members.map(m=><option key={m.id} value={m.id}>{m.full_name??m.id}</option>)}</select></label>}
      {kind==="human_takeover"&&<label className="text-sm"><input type="checkbox" checked={assign} onChange={e=>setAssign(e.target.checked)}/> Propose assignment on incoming messages. Human reply/takeover holds Bot until explicit synthetic resume.</label>}
      {kind==="unanswered_alert"&&<label className="text-sm">Wait minutes<input type="number" min={1} max={10080} className={field} value={alertMinutes} onChange={e=>setAlertMinutes(Number(e.target.value))}/></label>}
      <label className="text-sm">Priority (higher first)<input type="number" min={0} max={100} className={field} value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label>
      <label className="text-sm">Recipient cooldown minutes<input type="number" min={0} max={10080} className={field} value={cooldown} onChange={e=>setCooldown(Number(e.target.value))}/></label>
      <div className="border-t border-slate-200 pt-4 sm:col-span-2"><h3 className="text-sm font-semibold text-slate-900">Response</h3></div>
      <label className="text-sm">Reply / welcome template<textarea className={field} maxLength={2000} value={template} onChange={e=>setTemplate(e.target.value)}/></label>
      {kind==="welcome_away"&&<label className="text-sm">Away template<textarea className={field} maxLength={2000} value={away} onChange={e=>setAway(e.target.value)}/></label>}
      <button type="button" disabled={storageBusy||!channel||rules.length>=20} onClick={add} className="justify-self-start rounded-xl bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-100">Add rule</button>
    </fieldset>
    <h3 className="border-t border-slate-200 pt-4 text-sm font-semibold text-slate-900">Rules for this Bot</h3>
    <ul className="space-y-2">{rules.filter(r=>!selectedKind||r.kind===selectedKind).map(r=><li key={r.id} className="flex items-center justify-between gap-2 text-sm"><span>{r.name} · {labels[r.kind]} · Draft</span><button type="button" disabled={busy||storageBusy} onClick={()=>{setRules(current=>current.filter(x=>x.id!==r.id));setResult(null);}} className="rounded-lg border px-3 py-1">Remove draft</button></li>)}</ul>
    <div className="flex flex-wrap items-center gap-3">{!sharedSave&&<button type="button" disabled={busy||storageBusy||revision===null||!context?.canManage} onClick={()=>void save()} className="rounded-xl border border-violet-300 px-4 py-2 text-sm">Save disabled rules</button>}<span role="status" className="text-xs text-slate-600">{storageNote}</span></div><p className="text-xs text-slate-500">Saving persists all disabled rules for this channel; switching Bot menus keeps unfinished fields and rules. It does not activate automation. Saving never enables a worker or schedules delivery.</p><details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold text-slate-800">Test with sample conversation</summary><div className="mt-4 space-y-4">
    <p className="text-xs text-slate-500">Extended metadata is invented, scoped to this selected channel and never verified as a real Ad/referral/history. Comments and reference entries do not open a direct-message window.</p>
    <fieldset disabled={busy||storageBusy||!context?.canManage} className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Sample event<select className={field} value={eventKind} onChange={e=>setEventKind(e.target.value as DraftEvent["kind"])}><option value="customer">Customer message</option><option value="staff">Staff reply / takeover</option><option value="bot">Bot reply</option><option value="resume">Staff resumes Bot</option><option value="comment">Customer comment</option><option value="health">Recorded channel health</option><option value="referral">QR / reference entry</option><option value="cancel">Operator cancels follow-ups</option></select></label><label className="text-sm">Event time (UTC)<input className={field} type="datetime-local" value={eventAt} onChange={e=>setEventAt(e.target.value)}/></label><label className="text-sm sm:col-span-2">Invented message<textarea className={field} maxLength={2000} value={eventText} onChange={e=>setEventText(e.target.value)}/></label><label className="text-sm"><input type="checkbox" checked={firstContact} onChange={e=>setFirstContact(e.target.checked)}/> First customer contact</label><button type="button" disabled={busy||events.length>=100||!eventAt} onClick={addEvent} className="rounded-xl border px-4 py-2 text-sm">Add sample event</button></fieldset>
    <fieldset disabled={busy||storageBusy||!context?.canManage} className="grid gap-3 disabled:opacity-60 sm:grid-cols-2">
      {eventKind==="customer"&&<><label className="text-sm">Synthetic referral Ad ID (optional)<input className={field} value={sampleAd} onChange={e=>setSampleAd(e.target.value)}/></label><label className="text-sm">Synthetic previous conversations (0 means new)<input className={field} type="number" min={0} max={10000} value={samplePrevious} onChange={e=>setSamplePrevious(Number(e.target.value))}/></label>{samplePrevious>0&&<label className="text-sm">Synthetic prior last seen (UTC)<input className={field} type="datetime-local" value={sampleLastSeen} onChange={e=>setSampleLastSeen(e.target.value)}/></label>}</>}
      {eventKind==="comment"&&<><label className="text-sm">Synthetic Page_post ID<input className={field} value={samplePost} onChange={e=>setSamplePost(e.target.value)}/></label><label className="text-sm">Synthetic comment ID<input className={field} value={sampleComment} onChange={e=>setSampleComment(e.target.value)}/></label><label className="text-sm">Synthetic comment parent<select className={field} value={sampleParent} onChange={e=>setSampleParent(e.target.value)}><option value="first">Post itself (first-level)</option><option value="nested">Another comment (nested)</option><option value="unknown">Unknown parent</option></select></label><label className="text-sm"><input type="checkbox" checked={sampleDeleted} onChange={e=>setSampleDeleted(e.target.checked)}/> Deleted comment</label></>}
      {(eventKind==="referral"||(eventKind==="customer"&&kind==="qr_ref_flow"))&&<label className="text-sm">Synthetic public campaign reference<input className={field} value={sampleRef} onChange={e=>setSampleRef(e.target.value)}/></label>}
    </fieldset>
    <ol className="space-y-1 text-sm">{events.map(e=><li key={e.id}>{e.kind} · {e.at} · {e.text}</li>)}</ol>
    <p className="text-xs text-slate-500">Use invented text, not customer data. Maximum 100 events. Tests use the current clock; automated replies require a direct-customer hypothetical 24-hour window.</p>
    <div className="flex gap-2"><button type="button" disabled={!rules.some(rule=>!selectedKind||rule.kind===selectedKind)||!events.length||!context?.canManage||busy} onClick={()=>void test()} className="rounded-xl border px-4 py-2 text-sm">Test draft plan</button><button type="button" disabled={busy||storageBusy} onClick={clearCurrent} className="rounded-xl border px-4 py-2 text-sm">{selectedKind?"Clear this Bot in editor":"Clear session drafts"}</button></div>
    <button type="button" disabled={!channel||storageBusy||busy} onClick={()=>void loadHistory()} className="rounded-xl border px-4 py-2 text-sm">Load recent execution history</button>
    {history&&<div className="space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p>Latest {history.length} job(s). No background refresh.</p><ul>{history.filter(job=>!selectedKind||job.action.ruleKind===selectedKind||rules.some(rule=>rule.id===job.rule_id&&rule.kind===selectedKind)).map(job=><li key={job.id} className="whitespace-pre-wrap break-words">{job.action.kind}: {job.status}{job.reason?" — "+job.reason:""}{job.action.url?" — "+job.action.url:""}{["context","health"].includes(job.action.kind)&&job.action.text?" — "+job.action.text:""}</li>)}</ul></div>}
    {result&&<div role="status" className="space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p>No actions executed. {result.length} draft plan item(s).</p><ul className="space-y-2">{result.map(a=><li key={a.key} className="whitespace-pre-wrap break-words">{a.kind} · {a.status}{a.text?": "+a.text:""}{a.memberId?" · "+(context?.members.find(m=>m.id===a.memberId)?.full_name??"Selected staff"):""}{a.dueAt?" · due "+a.dueAt:""}{a.reason?" · "+a.reason:""}{a.url?" · QR payload: "+a.url:""}</li>)}</ul></div>}
</div></details>
  </section>;
}
