"use client";
import { useEffect, useState } from "react";
import { DRAFT_KINDS, parseDraftRules, type DraftKind, type DraftRule, type DraftEvent, type DraftAction } from "@/lib/bot/draft-rules";
type Context={businessId:string;canManage:boolean;pages:{id:string;account_name:string|null;platform:string}[];members:{id:string;full_name:string|null}[]};
const labels:Record<DraftKind,string>={welcome_away:"Welcome / Away",keyword_faq:"Keyword FAQ",human_takeover:"Autoassign / Human takeover",unanswered_alert:"Unanswered staff alert",conversation_menu:"Conversation menu"};
const field="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm";
export function BotDraftSettings(){
  const [context,setContext]=useState<Context|null>(null),[error,setError]=useState(""),[channel,setChannel]=useState(""),[rules,setRules]=useState<DraftRule[]>([]);
  const [kind,setKind]=useState<DraftKind>("welcome_away"),[name,setName]=useState(""),[template,setTemplate]=useState(""),[away,setAway]=useState(""),[keywords,setKeywords]=useState(""),[member,setMember]=useState("");
  const [timezone,setTimezone]=useState("UTC"),[start,setStart]=useState("09:00"),[end,setEnd]=useState("17:00"),[priority,setPriority]=useState(50),[cooldown,setCooldown]=useState(60),[alertMinutes,setAlertMinutes]=useState(15),[assign,setAssign]=useState(true);
  const [menu,setMenu]=useState(""),[events,setEvents]=useState<DraftEvent[]>([]),[result,setResult]=useState<DraftAction[]|null>(null),[busy,setBusy]=useState(false);
  const [eventKind,setEventKind]=useState<DraftEvent["kind"]>("customer"),[eventText,setEventText]=useState(""),[firstContact,setFirstContact]=useState(false),[eventAt,setEventAt]=useState(()=>new Date().toISOString().slice(0,16));
  useEffect(()=>{const abort=new AbortController();void fetch("/api/facebook/auto-reply?scope=drafts",{signal:abort.signal,cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error??"Drafts unavailable");setContext(data);setTimezone(Intl.DateTimeFormat().resolvedOptions().timeZone);}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort();},[]);
  const reset=()=>{setRules([]);setEvents([]);setResult(null);};
  function add(){if(!context)return;setError("");const minutes=(s:string)=>{const [h,m]=s.split(":").map(Number);return h*60+m;};
    const rule:DraftRule={id:crypto.randomUUID(),mode:"draft",businessId:context.businessId,channelId:channel,kind,name,template,awayTemplate:away,keywords:keywords.split(",").map(x=>x.trim()).filter(Boolean),timezone,hours:[1,2,3,4,5].map(day=>({day,start:minutes(start),end:minutes(end)})),priority,cooldownMinutes:cooldown,memberIds:member?[member]:[],assignOnIncoming:assign,alertMinutes,menu:menu.split("\n").filter(x=>x.trim()).map(row=>{const split=row.indexOf("|");return {label:row.slice(0,split).trim(),reply:row.slice(split+1).trim()};})};
    try{if(kind==="conversation_menu"&&menu.split("\n").filter(x=>x.trim()).some(x=>!x.includes("|")))throw Error("Separate each menu label and reply with |.");parseDraftRules([...rules,rule],{businessId:context.businessId,channelId:channel});setRules(current=>[...current,rule]);setResult(null);}catch(e){setError((e as Error).message)}
  }
  async function test(){setBusy(true);setError("");setResult(null);try{const response=await fetch("/api/facebook/auto-reply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"draftPreview",channelId:channel,rules,events,now:new Date().toISOString()})});const data=await response.json();if(!response.ok)throw Error(data.error);setResult(data.actions);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="space-y-4 rounded-2xl border border-violet-200 bg-white p-4 sm:p-6" aria-labelledby="bot-drafts-heading">
    <h2 id="bot-drafts-heading" className="text-xl font-semibold">Bot drafts · Stage 1</h2>
    <p className="text-sm text-slate-600">Draft / synthetic test only. Live execution unavailable. Nothing is saved to the workspace, sent, assigned, alerted or queued. Drafts last only while this editor is open and are separate from enabled comment rules.</p>
    {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
    <fieldset disabled={!context?.canManage||busy} className="grid gap-4 disabled:opacity-60 sm:grid-cols-2">
      <label className="text-sm">Connected channel<select className={field} value={channel} onChange={e=>{setChannel(e.target.value);reset();}}><option value="">Choose a Facebook Page</option>{context?.pages.map(p=><option key={p.id} value={p.id} disabled={p.platform!=="facebook"}>{p.account_name??p.id}{p.platform!=="facebook"?" · unavailable":" · draft only"}</option>)}</select></label>
      <label className="text-sm">Draft type<select className={field} value={kind} onChange={e=>setKind(e.target.value as DraftKind)}>{DRAFT_KINDS.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label>
      <label className="text-sm">Name<input className={field} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label>
      <label className="text-sm">Keywords / menu command (comma separated)<input className={field} value={keywords} onChange={e=>setKeywords(e.target.value)}/></label>
      <label className="text-sm">Reply / welcome template<textarea className={field} maxLength={2000} value={template} onChange={e=>setTemplate(e.target.value)}/></label>
      {kind==="welcome_away"&&<><label className="text-sm">Away template<textarea className={field} maxLength={2000} value={away} onChange={e=>setAway(e.target.value)}/></label><label className="text-sm">Business timezone<input className={field} value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><div className="flex gap-2"><label className="text-sm">Monday–Friday opens<input type="time" className={field} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm">Closes<input type="time" className={field} value={end} onChange={e=>setEnd(e.target.value)}/></label></div></>}
      {kind==="conversation_menu"&&<label className="text-sm sm:col-span-2">Choices: one Label | Reply per line<textarea className={field} value={menu} onChange={e=>setMenu(e.target.value)}/><span className="text-xs text-slate-500">Text-choice preview; provider quick-reply buttons are unavailable.</span></label>}
      {(kind==="human_takeover"||kind==="unanswered_alert")&&<label className="text-sm">Existing workspace staff<select className={field} value={member} onChange={e=>setMember(e.target.value)}><option value="">Choose staff</option>{context?.members.map(m=><option key={m.id} value={m.id}>{m.full_name??m.id}</option>)}</select></label>}
      {kind==="human_takeover"&&<label className="text-sm"><input type="checkbox" checked={assign} onChange={e=>setAssign(e.target.checked)}/> Propose assignment on incoming messages. Human reply/takeover holds Bot until explicit synthetic resume.</label>}
      {kind==="unanswered_alert"&&<label className="text-sm">Wait minutes<input type="number" min={1} max={10080} className={field} value={alertMinutes} onChange={e=>setAlertMinutes(Number(e.target.value))}/></label>}
      <label className="text-sm">Priority (higher first)<input type="number" min={0} max={100} className={field} value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label>
      <label className="text-sm">Recipient cooldown minutes<input type="number" min={0} max={10080} className={field} value={cooldown} onChange={e=>setCooldown(Number(e.target.value))}/></label>
      <button type="button" disabled={!channel||rules.length>=20} onClick={add} className="rounded-xl border border-violet-300 px-4 py-2 text-sm">Add session draft</button>
    </fieldset>
    <ul className="space-y-2">{rules.map(r=><li key={r.id} className="flex items-center justify-between gap-2 text-sm"><span>{r.name} · {labels[r.kind]} · Draft</span><button type="button" disabled={busy} onClick={()=>{setRules(current=>current.filter(x=>x.id!==r.id));setResult(null);}} className="rounded-lg border px-3 py-1">Remove draft</button></li>)}</ul>
    <h3 className="font-medium">Sample conversation</h3>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Sample event<select className={field} value={eventKind} onChange={e=>setEventKind(e.target.value as DraftEvent["kind"])}><option value="customer">Customer message</option><option value="staff">Staff reply / takeover</option><option value="bot">Bot reply</option><option value="resume">Staff resumes Bot</option></select></label><label className="text-sm">Event time (UTC)<input className={field} type="datetime-local" value={eventAt} onChange={e=>setEventAt(e.target.value)}/></label><label className="text-sm sm:col-span-2">Invented message<textarea className={field} maxLength={2000} value={eventText} onChange={e=>setEventText(e.target.value)}/></label><label className="text-sm"><input type="checkbox" checked={firstContact} onChange={e=>setFirstContact(e.target.checked)}/> First customer contact</label><button type="button" disabled={busy||events.length>=100||!eventAt} onClick={()=>{setEvents(current=>[...current,{id:crypto.randomUUID(),conversationId:"sample-conversation",recipientId:"sample-customer",kind:eventKind,at:new Date(eventAt+"Z").toISOString(),text:eventText,firstContact}]);setResult(null);}} className="rounded-xl border px-4 py-2 text-sm">Add sample event</button></div>
    <ol className="space-y-1 text-sm">{events.map(e=><li key={e.id}>{e.kind} · {e.at} · {e.text}</li>)}</ol>
    <p className="text-xs text-slate-500">Use invented text, not customer data. Maximum 100 events. Tests use the current clock; automated replies require a direct-customer hypothetical 24-hour window.</p>
    <div className="flex gap-2"><button type="button" disabled={!rules.length||!events.length||!context?.canManage||busy} onClick={()=>void test()} className="rounded-xl border px-4 py-2 text-sm">Test draft plan</button><button type="button" disabled={busy} onClick={reset} className="rounded-xl border px-4 py-2 text-sm">Clear session drafts</button></div>
    {result&&<div role="status" className="space-y-2 rounded-xl bg-slate-50 p-3 text-sm"><p>No actions executed. {result.length} proposed plan item(s).</p><ul className="space-y-2">{result.map(a=><li key={a.key} className="whitespace-pre-wrap break-words">{a.kind} · {a.status}{a.text?": "+a.text:""}{a.memberId?" · "+(context?.members.find(m=>m.id===a.memberId)?.full_name??"Selected staff"):""}{a.dueAt?" · due "+a.dueAt:""}</li>)}</ul></div>}
  </section>;
}
